// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT MainPanelRoomCtrl

lv_obj_t *ui_MainPanelRoomCtrl_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_MainPanelRoomCtrl;
cui_MainPanelRoomCtrl = lv_obj_create(comp_parent);
lv_obj_set_width( cui_MainPanelRoomCtrl, 149);
lv_obj_set_height( cui_MainPanelRoomCtrl, 61);
lv_obj_set_x( cui_MainPanelRoomCtrl, -423 );
lv_obj_set_y( cui_MainPanelRoomCtrl, 258 );
lv_obj_set_align( cui_MainPanelRoomCtrl, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_MainPanelRoomCtrl, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MAINPANELROOMCTRL_NUM);
children[UI_COMP_MAINPANELROOMCTRL_MAINPANELROOMCTRL] = cui_MainPanelRoomCtrl;
lv_obj_add_event_cb(cui_MainPanelRoomCtrl, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_MainPanelRoomCtrl, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_MainPanelRoomCtrl_create_hook(cui_MainPanelRoomCtrl);
return cui_MainPanelRoomCtrl; 
}

