// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT Panel3

lv_obj_t *ui_Panel3_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Panel3;
cui_Panel3 = lv_obj_create(comp_parent);
lv_obj_set_width( cui_Panel3, 100);
lv_obj_set_height( cui_Panel3, 50);
lv_obj_set_align( cui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL3_NUM);
children[UI_COMP_PANEL3_PANEL3] = cui_Panel3;
lv_obj_add_event_cb(cui_Panel3, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Panel3, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Panel3_create_hook(cui_Panel3);
return cui_Panel3; 
}

