// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
lv_obj_t *ui_ScreenMain;
lv_obj_t *ui_MainBtnCall;
lv_obj_t *ui_MainPanelSet;
lv_obj_t *ui_MainBtnSet;
lv_obj_t *ui_MainLabelSet;
lv_obj_t *ui_MainPanelRoomCtrl;
lv_obj_t *ui_MainBtnRoomCtrl;
lv_obj_t *ui_MainLabelRoomCtrl;
lv_obj_t *ui_MainPanelMusic;
lv_obj_t *ui_MainBtnMusic;
lv_obj_t *ui_MainLabelMusic;
lv_obj_t *ui_MainLabelDay;
lv_obj_t *ui_MainLabelMsg;
lv_obj_t *ui_MainLabelErr;
lv_obj_t *ui_MainLabelTime;
lv_obj_t *ui_MainIconWiFi;


// SCREEN: ui_ScreenConfirm
void ui_ScreenConfirm_screen_init(void);
lv_obj_t *ui_ScreenConfirm;
lv_obj_t *ui_ConfirmPanelTtitle;
lv_obj_t *ui_ConfirmBtnBack;
lv_obj_t *ui_ConfirmLabelTime;
lv_obj_t *ui_ConfirmPanelKey;
lv_obj_t *ui_ConfirmBtn2;
lv_obj_t *ui_ConfirmLabel2;
lv_obj_t *ui_ConfirmBtn1;
lv_obj_t *ui_ConfirmLabel1;
lv_obj_t *ui_ConfirmBtn3;
lv_obj_t *ui_ConfirmLabel3;
lv_obj_t *ui_ConfirmBtn4;
lv_obj_t *ui_ConfirmLabel4;
lv_obj_t *ui_ConfirmBtn5;
lv_obj_t *ui_ConfirmLabel5;
lv_obj_t *ui_ConfirmBtn6;
lv_obj_t *ui_ConfirmLabel6;
lv_obj_t *ui_ConfirmBtn7;
lv_obj_t *ui_ConfirmLabel7;
lv_obj_t *ui_ConfirmBtn8;
lv_obj_t *ui_ConfirmLabel8;
lv_obj_t *ui_ConfirmBtn9;
lv_obj_t *ui_ConfirmLabel9;
lv_obj_t *ui_ConfirmBtn0;
lv_obj_t *ui_ConfirmLabel0;
lv_obj_t *ui_ConfirmBtnCancel;
lv_obj_t *ui_ConfirmLabelCancel;
lv_obj_t *ui_ConfirmBtnConfirm;
lv_obj_t *ui_ConfirmLabelConfirm;
lv_obj_t *ui_ConfirmPanelInput;
lv_obj_t *ui_ConfirmLabelInput;
lv_obj_t *ui_ConfirmBtnReset;
lv_obj_t *ui_ConfirmLabelReset;
lv_obj_t *ui_ConfirmImgReset;
lv_obj_t *ui_ConfirmBtnInit;
lv_obj_t *ui_ConfirmLabelinit;
lv_obj_t *ui_ConfirmImgReinit;


// SCREEN: ui_ScreenConfig
void ui_ScreenConfig_screen_init(void);
lv_obj_t *ui_ScreenConfig;
lv_obj_t *ui_ConfigPanelTtitle;
lv_obj_t *ui_ConfigBtnBack;
lv_obj_t *ui_ConfigLabelTime;
lv_obj_t *ui_ConfigPanelList;
lv_obj_t *ui_ConfigPanelSetting1;
lv_obj_t *ui_ConfigPanelSetting2;
lv_obj_t *ui_ConfigLabelSetting;
lv_obj_t *ui_ConfigPanelRegister1;
lv_obj_t *ui_ConfigPanelRegister2;
lv_obj_t *ui_ConfigLabelRegister;
lv_obj_t *ui_ConfigPanelSubDev1;
lv_obj_t *ui_ConfigPanelSubDev2;
lv_obj_t *ui_ConfigLabelSubDev;
lv_obj_t *ui_ConfigPanelNet1;
lv_obj_t *ui_ConfigPanelNet2;
lv_obj_t *ui_ConfigLabelNet;
lv_obj_t *ui_ConfigPanelVersion1;
lv_obj_t *ui_ConfigPanelVersion2;
lv_obj_t *ui_ConfigLabelVersion;
lv_obj_t *ui_ConfigPanelAbout1;
lv_obj_t *ui_ConfigPanelAbout2;
lv_obj_t *ui_ConfigLabelAbout;
lv_obj_t *ui_ConfigListLine1;
lv_obj_t *ui_ConfigListLine2;
lv_obj_t *ui_ConfigListLine3;
lv_obj_t *ui_ConfigListLine4;
lv_obj_t *ui_ConfigListLine5;
lv_obj_t *ui_ConfigListLine6;
lv_obj_t *ui_ConfigListLine7;
lv_obj_t *ui_ConfigListLine8;
lv_obj_t *ui_ConfigPanelForSetting;
lv_obj_t *ui_ConfigDecoration1;
lv_obj_t *ui_ConfigLabelData;
lv_obj_t *ui_ConfigLabelLight1;
lv_obj_t *ui_ConfigSliderLight;
lv_obj_t *ui_ConfigLabelLight2;
lv_obj_t *ui_ConfigLabelVoice1;
lv_obj_t *ui_ConfigSliderVoice;
lv_obj_t *ui_ConfigLabelVoice2;
lv_obj_t *ui_ConfigLabelSaverLight1;
lv_obj_t *ui_ConfigSliderSaverLight;
lv_obj_t *ui_ConfigLabelSaverLight2;
lv_obj_t *ui_ConfigLabelEnableVoice;
lv_obj_t *ui_ConfigSwEnableVoice;
lv_obj_t *ui_ConfigLabelEnableDebug;
lv_obj_t *ui_ConfigSwEnableDebug;
lv_obj_t *ui_ConfigDecoration2;
lv_obj_t *ui_ConfigLabelSaverSet;
lv_obj_t *ui_ConfigLabelEnableSaver;
lv_obj_t *ui_ConfigSwEnableSaver;
lv_obj_t *ui_ConfigLabelSaverTime1;
lv_obj_t *ui_ConfigPanelSaverTime;
lv_obj_t *ui_ConfigLabelSaverTime2;
lv_obj_t *ui_ConfigPanelVoiceSet;
lv_obj_t *ui_ConfigLabelVoiceSet;
lv_obj_t *ui_ConfigIconVoiceSet;
lv_obj_t *ui_ConfigPanelDebug;
lv_obj_t *ui_ConfigLabelDebugMsg1;
lv_obj_t *ui_ConfigLabelDebugMsg2;
lv_obj_t *ui_ConfigLabelDebugMsg3;
lv_obj_t *ui_ConfigLabelDebugMsg4;
lv_obj_t *ui_ConfigLabelDebugMsg5;
lv_obj_t *ui_ConfigLabelDebugMsg6;
lv_obj_t *ui_ConfigLabelDebugMsg7;
lv_obj_t *ui_ConfigLabelDebugMsg8;
lv_obj_t *ui_ConfigLabelDebugMsg9;
lv_obj_t *ui_ConfigLabelDebugMsg10;
lv_obj_t *ui_ConfigLabelDebugMsg11;
lv_obj_t *ui_ConfigLabelDebugMsg12;
lv_obj_t *ui_ConfigLabelDebugMsg13;
lv_obj_t *ui_ConfigLabelDebugMsg14;
lv_obj_t *ui_ConfigLabelDebugMsg15;
lv_obj_t *ui_ConfigDebugTextarea;
lv_obj_t *ui_ConfigPanelForRegister;
lv_obj_t *ui_ConfigBtnActivate;
lv_obj_t *ui_ConfirmLabelActivate;
lv_obj_t *ui_ConfigPanelForSubDev;
lv_obj_t *ui_ConfigBtnBLE;
lv_obj_t *ui_ConfigIconBLE;
lv_obj_t *ui_ConfigLabelBLE;
lv_obj_t *ui_ConfigBtnDevLoRa;
lv_obj_t *ui_ConfigIconLoRa;
lv_obj_t *ui_ConfigLabelLoRa;
lv_obj_t *ui_ConfigBtnSubDev;
lv_obj_t *ui_ConfigIconSubDev;
lv_obj_t *ui_ConfigLabelSubDev2;
lv_obj_t *ui_ConfigPanelForNet;
lv_obj_t *ui_ConfigLabelNetTest1;
lv_obj_t *ui_ConfigBtnNetTest;
lv_obj_t *ui_ConfigLabelNetTest;
lv_obj_t *ui_ConfigPanelWired;
lv_obj_t *ui_ConfigLabelWired1;
lv_obj_t *ui_ConfigLabelWired2;
lv_obj_t *ui_ConfigDecoration3;
lv_obj_t *ui_ConfigSwNetEnable;
lv_obj_t *ui_ConfigPanelWLAN;
lv_obj_t *ui_ConfigLabelWLAN1;
lv_obj_t *ui_ConfigLabelWLAN2;
lv_obj_t *ui_ConfigLabelNetEnable;
lv_obj_t *ui_ConfigPanelIP;
lv_obj_t *ui_ConfigDecoration10;
lv_obj_t *ui_ConfigDecoration11;
lv_obj_t *ui_ConfigCheckNoDHCP;
lv_obj_t *ui_ConfigCheckDHCP;
lv_obj_t *ui_ConfigLabelIP3;
lv_obj_t *ui_ConfigLabelGateway1;
lv_obj_t *ui_ConfigLabelNetmask1;
lv_obj_t *ui_ConfigLabelMainDNS1;
lv_obj_t *ui_ConfigLabelSubDNS1;
lv_obj_t *ui_ConfigBtnIP;
lv_obj_t *ui_ConfigLabelIP4;
lv_obj_t *ui_ConfigBtnGateway;
lv_obj_t *ui_ConfigLabelGateway2;
lv_obj_t *ui_ConfigBtnNetMask;
lv_obj_t *ui_ConfigLabelNetMask2;
lv_obj_t *ui_ConfigBtnMainDNS;
lv_obj_t *ui_ConfigLabelMainDNS2;
lv_obj_t *ui_ConfigBtnSubDNS;
lv_obj_t *ui_ConfigLabelSubDNS2;
lv_obj_t *ui_ConfigPanelForVersion;
lv_obj_t *ui_ConfigLabelAppUp1;
lv_obj_t *ui_ConfigDecoration4;
lv_obj_t *ui_ConfigPanelAppUp;
lv_obj_t *ui_ConfigLabelAppUp2;
lv_obj_t *ui_ConfigBtnReset;
lv_obj_t *ui_ConfigLabelReset;
lv_obj_t *ui_ConfigLabelAppUp3;
lv_obj_t *ui_ConfigPanelForAbout;
lv_obj_t *ui_ConfigLabelAppUp4;
lv_obj_t *ui_ConfigDecoration5;
lv_obj_t *ui_ConfirmBtnReset2;
lv_obj_t *ui_ConfirmLabelAppUp1;
lv_obj_t *ui_ConfigDecoration6;
lv_obj_t *ui_ConfigDecoration7;
lv_obj_t *ui_ConfigDecoration8;
lv_obj_t *ui_ConfigLabelIP1;
lv_obj_t *ui_ConfigLabelIP2;
lv_obj_t *ui_ConfigLabelSerialNum1;
lv_obj_t *ui_ConfigLabelSerialNum2;
lv_obj_t *ui_ConfigLabelLinuxVer1;
lv_obj_t *ui_ConfigLabelLinuxVer2;
lv_obj_t *ui_ConfigLabelManufacturer1;
lv_obj_t *ui_ConfigLabelManufacturer2;
lv_obj_t *ui_ConfigLabelSoftVer1;
lv_obj_t *ui_ConfigLabelSoftVer2;
lv_obj_t *ui_ConfigLabelHardwareVer1;
lv_obj_t *ui_ConfigLabelHardwareVer2;
lv_obj_t *ui_ConfigLabelKernelVer1;
lv_obj_t *ui_ConfigLabelKernelVer2;
lv_obj_t *ui_ConfigLabelH5Ver1;
lv_obj_t *ui_ConfigLabelH5Ver2;
lv_obj_t *ui_ConfigPanelForDevList1;
lv_obj_t *ui_ConfigLabelDevList2;
lv_obj_t *ui_ConfigBtnRefreshDevList;
lv_obj_t *ui_ConfigLabelRefreshDevList;
lv_obj_t *ui_ConfigDecoration9;
lv_obj_t *ui_ConfigPanelForDevList2;
lv_obj_t *ui_ConfigPanelDevMsg;
lv_obj_t *ui_ConfigLabelDevName;
lv_obj_t *ui_ConfigLabelDevState;
lv_obj_t *ui_ConfigLabelDevVer;
lv_obj_t *ui_ConfigLabelDevOperation;
lv_obj_t *ui_ConfigPanelDecoration10;
lv_obj_t *ui_TempPanel1;
lv_obj_t *ui_TempDecoration2;
lv_obj_t *ui_TempBtnManage1;
lv_obj_t *ui_TempLabelManage1;
lv_obj_t *ui_TempBtnUpdate1;
lv_obj_t *ui_TempLabelUpdate1;
lv_obj_t *ui_TempLabelDev1Name1;
lv_obj_t *ui_TempLabelDev1State1;
lv_obj_t *ui_TempLabelDev1Ver1;
lv_obj_t *ui_ConfigLabelNoSubDev;
lv_obj_t *ui_ConfigKeyboard;


// SCREEN: ui_ScreenVoiceSet
void ui_ScreenVoiceSet_screen_init(void);
lv_obj_t *ui_ScreenVoiceSet;
lv_obj_t *ui_VoicePanelTitle;
lv_obj_t *ui_VoiceBtnBack;
lv_obj_t *ui_VoiceLabelTime;
lv_obj_t *ui_VoiceDecoration;
lv_obj_t *ui_VoiceLabelSetting1;
lv_obj_t *ui_VoiceLabelSetting2;
lv_obj_t *ui_VoicePanel;
lv_obj_t *ui_VoiceSliderVolume;
lv_obj_t *ui_VoiceLabelVolume1;
lv_obj_t *ui_VoiceLabelVolume2;
lv_obj_t *ui_VoiceSliderTone;
lv_obj_t *ui_VoiceLabelTone1;
lv_obj_t *ui_VoiceLabelTone2;
lv_obj_t *ui_VoiceSliderPace;
lv_obj_t *ui_VoiceLabelPace1;
lv_obj_t *ui_VoiceLabelPace2;


// SCREEN: ui_ScreenRoomMain
void ui_ScreenRoomMain_screen_init(void);
lv_obj_t *ui_ScreenRoomMain;
lv_obj_t *ui_RoomMainPanelTtitle;
lv_obj_t *ui_RoomMainBtnBack;
lv_obj_t *ui_RoomMainLabelTime;
lv_obj_t *ui_RoomMainPanelSceneMode;
lv_obj_t *ui_RoomMainSceneModeLabel1;
lv_obj_t *ui_RoomMainBtnSceneMode;
lv_obj_t *ui_RoomMainSceneModeLabel3;
lv_obj_t *ui_RoomMainPanelAircon;
lv_obj_t *ui_RoomMainLabelAircon;
lv_obj_t *ui_RoomMainLabelTemp1;
lv_obj_t *ui_RoomMainLabelTemp2;
lv_obj_t *ui_RoomMainLabelAirconMode2;
lv_obj_t *ui_RoomMainLabelAirconMode1;
lv_obj_t *ui_RoomMainBtnAirconUp;
lv_obj_t *ui_RoomMainPanelAirconDown;
lv_obj_t *ui_RoomMainIconDegree;
lv_obj_t *ui_RoomMainBtnAirconMode;
lv_obj_t *ui_RoomMainBtnAirconWind;
lv_obj_t *ui_RoomMainBtnAirconDown;
lv_obj_t *ui_RoomMainBtnAirconSW;
lv_obj_t *ui_RoomMainLabelAirconSW;
lv_obj_t *ui_RoomMainPanelMainSw;
lv_obj_t *ui_RoomMainSw;
lv_obj_t *ui_RoomMainLabelSw;
lv_obj_t *ui_RoomMainPanelWindow;
lv_obj_t *ui_RoomMainLabelWindow;
lv_obj_t *ui_RoomMainIconWindow;
lv_obj_t *ui_RoomMainPanelLight;
lv_obj_t *ui_RoomMainIconLight;
lv_obj_t *ui_RoomMainLabelLight;


// SCREEN: ui_ScreenRoomWin
void ui_ScreenRoomWin_screen_init(void);
lv_obj_t *ui_ScreenRoomWin;
lv_obj_t *ui_RoomWinPanelTtitle;
lv_obj_t *ui_RoomWinBtnBack;
lv_obj_t *ui_RoomWinLabelTime;
lv_obj_t *ui_RoomWinPanelCtrl1;
lv_obj_t *ui_RoomWinPanelGauze;
lv_obj_t *ui_RoomWinLabelGauze;
lv_obj_t *ui_RoomWinIconGauze;
lv_obj_t *ui_RoomWinPanelCloth;
lv_obj_t *ui_RoomWinLabelCloth;
lv_obj_t *ui_RoomWinIconCloth;
lv_obj_t *ui_RoomWinLabel;
lv_obj_t *ui_RoomWinBtnOpen1;
lv_obj_t *ui_RoomWinBtnPause1;
lv_obj_t *ui_RoomWinBtnClose1;
lv_obj_t *ui_RoomWinPanelCtrl2;
lv_obj_t *ui_RoomWinBtnOpen2;
lv_obj_t *ui_RoomWinLabelOpen;
lv_obj_t *ui_RoomWinIconOpen;
lv_obj_t *ui_RoomWinBtnClose2;
lv_obj_t *ui_RoomWinLabelClose;
lv_obj_t *ui_RoomWinIconClose;
lv_obj_t *ui_RoomWinBtnBack1;
lv_obj_t *ui_RoomWinLabelBack;


// SCREEN: ui_ScreenRoomRelay
void ui_ScreenRoomRelay_screen_init(void);
lv_obj_t *ui_ScreenRoomRelay;
lv_obj_t *ui_RoomRelayPanelTtitle;
lv_obj_t *ui_RoomRelayBtnBack;
lv_obj_t *ui_RoomRelayLabelTime;
lv_obj_t *ui_RoomRelayBtnOpen4;
lv_obj_t *ui_RoomRelayLabelOpen1;
lv_obj_t *ui_RoomRelayIconOpen1;
lv_obj_t *ui_RoomRelayBtnBack1;
lv_obj_t *ui_RoomRelayLabelBack;
lv_obj_t *ui_RoomRelayBtnOpen3;
lv_obj_t *ui_RoomRelayLabelOpen2;
lv_obj_t *ui_RoomRelayIconOpen2;
lv_obj_t *ui_RoomRelayBtnRelay9;
lv_obj_t *ui_RoomRelayLabelRelay9;
lv_obj_t *ui_RoomRelaySwRelay9;
lv_obj_t *ui_RoomRelayBtnRelay11;
lv_obj_t *ui_RoomRelayLabelRelay11;
lv_obj_t *ui_RoomRelaySwRelay11;
lv_obj_t *ui_RoomRelayBtnRelay5;
lv_obj_t *ui_RoomRelayLabelRelay5;
lv_obj_t *ui_RoomRelaySwRelay5;
lv_obj_t *ui_RoomRelayBtnRelay10;
lv_obj_t *ui_RoomRelayLabelRelay10;
lv_obj_t *ui_RoomRelaySwRelay10;
lv_obj_t *ui_RoomRelayBtnRelay7;
lv_obj_t *ui_RoomRelayLabelRelay7;
lv_obj_t *ui_RoomRelaySwRelay7;
lv_obj_t *ui_RoomRelayBtnRelay8;
lv_obj_t *ui_RoomRelayLabelRelay8;
lv_obj_t *ui_RoomRelaySwRelay8;
lv_obj_t *ui_RoomRelayBtnRelay12;
lv_obj_t *ui_RoomRelayLabelRelay12;
lv_obj_t *ui_RoomRelaySwRelay12;
lv_obj_t *ui_RoomRelayBtnRelay13;
lv_obj_t *ui_RoomRelayLabelRelay13;
lv_obj_t *ui_RoomRelaySwRelay13;


// SCREEN: ui_ScreenDebug
void ui_ScreenDebug_screen_init(void);
lv_obj_t *ui_ScreenDebug;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_Panel7;


// SCREEN: ui_ScreenMusic
void ui_ScreenMusic_screen_init(void);
lv_obj_t *ui_ScreenMusic;
lv_obj_t *ui_MusicPanelTtitle;
lv_obj_t *ui_MusicBtnBack;
lv_obj_t *ui_MusicLabelTime;
lv_obj_t *ui_MusicPanelMain;
lv_obj_t *ui_MusicBarMusicBar;
lv_obj_t *ui_MusicPanelMusicList;
lv_obj_t *ui_MusicPanelMusic1;
lv_obj_t *ui_MusicLabelMusic1;
lv_obj_t *ui_MusicBtnNext;
lv_obj_t *ui_MusicLabelNext;
lv_obj_t *ui_MusicBtnStart;
lv_obj_t *ui_MusicLabelStart;
lv_obj_t *ui_MusicBtnLast;
lv_obj_t *ui_MusicLabelLast;
lv_obj_t *ui_MusicBtnVoice;
lv_obj_t *ui_MusicLabelVoice;
lv_obj_t *ui_MusicPanelMusicNow;
lv_obj_t *ui_MusicLabelMusicNow;
lv_obj_t *ui_MusicBtnMode;
lv_obj_t *ui_MusicLabelMode;
lv_obj_t *ui_MusicLabelMusicBarLabel;
lv_obj_t *ui_MusicIcon1;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_ble_icon48x[1] = {&ui_img_ble_icon48x68_png};
const lv_img_dsc_t *ui_imgset_lora_iconx[1] = {&ui_img_lora_icon64x64_png};
const lv_img_dsc_t *ui_imgset_1226928067[1] = {&ui_img_763119327};
const lv_img_dsc_t *ui_imgset_1703611654[1] = {&ui_img_89075366};
const lv_img_dsc_t *ui_imgset_95929318[1] = {&ui_img_1595275858};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ScreenMain_screen_init();
ui_ScreenConfirm_screen_init();
ui_ScreenConfig_screen_init();
ui_ScreenVoiceSet_screen_init();
ui_ScreenRoomMain_screen_init();
ui_ScreenRoomWin_screen_init();
ui_ScreenRoomRelay_screen_init();
ui_ScreenDebug_screen_init();
ui_ScreenMusic_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScreenMain);
}
