// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
extern lv_obj_t *ui_ScreenMain;
extern lv_obj_t *ui_MainBtnCall;
extern lv_obj_t *ui_MainPanelSet;
extern lv_obj_t *ui_MainBtnSet;
extern lv_obj_t *ui_MainLabelSet;
extern lv_obj_t *ui_MainPanelRoomCtrl;
extern lv_obj_t *ui_MainBtnRoomCtrl;
extern lv_obj_t *ui_MainLabelRoomCtrl;
extern lv_obj_t *ui_MainPanelMusic;
extern lv_obj_t *ui_MainBtnMusic;
extern lv_obj_t *ui_MainLabelMusic;
extern lv_obj_t *ui_MainLabelDay;
extern lv_obj_t *ui_MainLabelMsg;
extern lv_obj_t *ui_MainLabelErr;
extern lv_obj_t *ui_MainLabelTime;
extern lv_obj_t *ui_MainIconWiFi;
// SCREEN: ui_ScreenConfirm
void ui_ScreenConfirm_screen_init(void);
extern lv_obj_t *ui_ScreenConfirm;
extern lv_obj_t *ui_ConfirmPanelTtitle;
extern lv_obj_t *ui_ConfirmBtnBack;
extern lv_obj_t *ui_ConfirmLabelTime;
extern lv_obj_t *ui_ConfirmPanelKey;
extern lv_obj_t *ui_ConfirmBtn2;
extern lv_obj_t *ui_ConfirmLabel2;
extern lv_obj_t *ui_ConfirmBtn1;
extern lv_obj_t *ui_ConfirmLabel1;
extern lv_obj_t *ui_ConfirmBtn3;
extern lv_obj_t *ui_ConfirmLabel3;
extern lv_obj_t *ui_ConfirmBtn4;
extern lv_obj_t *ui_ConfirmLabel4;
extern lv_obj_t *ui_ConfirmBtn5;
extern lv_obj_t *ui_ConfirmLabel5;
extern lv_obj_t *ui_ConfirmBtn6;
extern lv_obj_t *ui_ConfirmLabel6;
extern lv_obj_t *ui_ConfirmBtn7;
extern lv_obj_t *ui_ConfirmLabel7;
extern lv_obj_t *ui_ConfirmBtn8;
extern lv_obj_t *ui_ConfirmLabel8;
extern lv_obj_t *ui_ConfirmBtn9;
extern lv_obj_t *ui_ConfirmLabel9;
extern lv_obj_t *ui_ConfirmBtn0;
extern lv_obj_t *ui_ConfirmLabel0;
extern lv_obj_t *ui_ConfirmBtnCancel;
extern lv_obj_t *ui_ConfirmLabelCancel;
extern lv_obj_t *ui_ConfirmBtnConfirm;
extern lv_obj_t *ui_ConfirmLabelConfirm;
extern lv_obj_t *ui_ConfirmPanelInput;
extern lv_obj_t *ui_ConfirmLabelInput;
extern lv_obj_t *ui_ConfirmBtnReset;
extern lv_obj_t *ui_ConfirmLabelReset;
extern lv_obj_t *ui_ConfirmImgReset;
extern lv_obj_t *ui_ConfirmBtnInit;
extern lv_obj_t *ui_ConfirmLabelinit;
extern lv_obj_t *ui_ConfirmImgReinit;
// SCREEN: ui_ScreenConfig
void ui_ScreenConfig_screen_init(void);
extern lv_obj_t *ui_ScreenConfig;
extern lv_obj_t *ui_ConfigPanelTtitle;
extern lv_obj_t *ui_ConfigBtnBack;
extern lv_obj_t *ui_ConfigLabelTime;
extern lv_obj_t *ui_ConfigPanelList;
extern lv_obj_t *ui_ConfigPanelSetting1;
extern lv_obj_t *ui_ConfigPanelSetting2;
extern lv_obj_t *ui_ConfigLabelSetting;
extern lv_obj_t *ui_ConfigPanelRegister1;
extern lv_obj_t *ui_ConfigPanelRegister2;
extern lv_obj_t *ui_ConfigLabelRegister;
extern lv_obj_t *ui_ConfigPanelSubDev1;
extern lv_obj_t *ui_ConfigPanelSubDev2;
extern lv_obj_t *ui_ConfigLabelSubDev;
extern lv_obj_t *ui_ConfigPanelNet1;
extern lv_obj_t *ui_ConfigPanelNet2;
extern lv_obj_t *ui_ConfigLabelNet;
extern lv_obj_t *ui_ConfigPanelVersion1;
extern lv_obj_t *ui_ConfigPanelVersion2;
extern lv_obj_t *ui_ConfigLabelVersion;
extern lv_obj_t *ui_ConfigPanelAbout1;
extern lv_obj_t *ui_ConfigPanelAbout2;
extern lv_obj_t *ui_ConfigLabelAbout;
extern lv_obj_t *ui_ConfigListLine1;
extern lv_obj_t *ui_ConfigListLine2;
extern lv_obj_t *ui_ConfigListLine3;
extern lv_obj_t *ui_ConfigListLine4;
extern lv_obj_t *ui_ConfigListLine5;
extern lv_obj_t *ui_ConfigListLine6;
extern lv_obj_t *ui_ConfigListLine7;
extern lv_obj_t *ui_ConfigListLine8;
extern lv_obj_t *ui_ConfigPanelForSetting;
extern lv_obj_t *ui_ConfigDecoration1;
extern lv_obj_t *ui_ConfigLabelData;
extern lv_obj_t *ui_ConfigLabelLight1;
extern lv_obj_t *ui_ConfigSliderLight;
extern lv_obj_t *ui_ConfigLabelLight2;
extern lv_obj_t *ui_ConfigLabelVoice1;
extern lv_obj_t *ui_ConfigSliderVoice;
extern lv_obj_t *ui_ConfigLabelVoice2;
extern lv_obj_t *ui_ConfigLabelSaverLight1;
extern lv_obj_t *ui_ConfigSliderSaverLight;
extern lv_obj_t *ui_ConfigLabelSaverLight2;
extern lv_obj_t *ui_ConfigLabelEnableVoice;
extern lv_obj_t *ui_ConfigSwEnableVoice;
extern lv_obj_t *ui_ConfigLabelEnableDebug;
extern lv_obj_t *ui_ConfigSwEnableDebug;
extern lv_obj_t *ui_ConfigDecoration2;
extern lv_obj_t *ui_ConfigLabelSaverSet;
extern lv_obj_t *ui_ConfigLabelEnableSaver;
extern lv_obj_t *ui_ConfigSwEnableSaver;
extern lv_obj_t *ui_ConfigLabelSaverTime1;
extern lv_obj_t *ui_ConfigPanelSaverTime;
extern lv_obj_t *ui_ConfigLabelSaverTime2;
extern lv_obj_t *ui_ConfigPanelVoiceSet;
extern lv_obj_t *ui_ConfigLabelVoiceSet;
extern lv_obj_t *ui_ConfigIconVoiceSet;
extern lv_obj_t *ui_ConfigPanelDebug;
extern lv_obj_t *ui_ConfigLabelDebugMsg1;
extern lv_obj_t *ui_ConfigLabelDebugMsg2;
extern lv_obj_t *ui_ConfigLabelDebugMsg3;
extern lv_obj_t *ui_ConfigLabelDebugMsg4;
extern lv_obj_t *ui_ConfigLabelDebugMsg5;
extern lv_obj_t *ui_ConfigLabelDebugMsg6;
extern lv_obj_t *ui_ConfigLabelDebugMsg7;
extern lv_obj_t *ui_ConfigLabelDebugMsg8;
extern lv_obj_t *ui_ConfigLabelDebugMsg9;
extern lv_obj_t *ui_ConfigLabelDebugMsg10;
extern lv_obj_t *ui_ConfigLabelDebugMsg11;
extern lv_obj_t *ui_ConfigLabelDebugMsg12;
extern lv_obj_t *ui_ConfigLabelDebugMsg13;
extern lv_obj_t *ui_ConfigLabelDebugMsg14;
extern lv_obj_t *ui_ConfigLabelDebugMsg15;
extern lv_obj_t *ui_ConfigDebugTextarea;
extern lv_obj_t *ui_ConfigPanelForRegister;
extern lv_obj_t *ui_ConfigBtnActivate;
extern lv_obj_t *ui_ConfirmLabelActivate;
extern lv_obj_t *ui_ConfigPanelForSubDev;
extern lv_obj_t *ui_ConfigBtnBLE;
extern lv_obj_t *ui_ConfigIconBLE;
extern lv_obj_t *ui_ConfigLabelBLE;
extern lv_obj_t *ui_ConfigBtnDevLoRa;
extern lv_obj_t *ui_ConfigIconLoRa;
extern lv_obj_t *ui_ConfigLabelLoRa;
extern lv_obj_t *ui_ConfigBtnSubDev;
extern lv_obj_t *ui_ConfigIconSubDev;
extern lv_obj_t *ui_ConfigLabelSubDev2;
extern lv_obj_t *ui_ConfigPanelForNet;
extern lv_obj_t *ui_ConfigLabelNetTest1;
extern lv_obj_t *ui_ConfigBtnNetTest;
extern lv_obj_t *ui_ConfigLabelNetTest;
extern lv_obj_t *ui_ConfigPanelWired;
extern lv_obj_t *ui_ConfigLabelWired1;
extern lv_obj_t *ui_ConfigLabelWired2;
extern lv_obj_t *ui_ConfigDecoration3;
extern lv_obj_t *ui_ConfigSwNetEnable;
extern lv_obj_t *ui_ConfigPanelWLAN;
extern lv_obj_t *ui_ConfigLabelWLAN1;
extern lv_obj_t *ui_ConfigLabelWLAN2;
extern lv_obj_t *ui_ConfigLabelNetEnable;
extern lv_obj_t *ui_ConfigPanelIP;
extern lv_obj_t *ui_ConfigDecoration10;
extern lv_obj_t *ui_ConfigDecoration11;
extern lv_obj_t *ui_ConfigCheckNoDHCP;
extern lv_obj_t *ui_ConfigCheckDHCP;
extern lv_obj_t *ui_ConfigLabelIP3;
extern lv_obj_t *ui_ConfigLabelGateway1;
extern lv_obj_t *ui_ConfigLabelNetmask1;
extern lv_obj_t *ui_ConfigLabelMainDNS1;
extern lv_obj_t *ui_ConfigLabelSubDNS1;
extern lv_obj_t *ui_ConfigBtnIP;
extern lv_obj_t *ui_ConfigLabelIP4;
extern lv_obj_t *ui_ConfigBtnGateway;
extern lv_obj_t *ui_ConfigLabelGateway2;
extern lv_obj_t *ui_ConfigBtnNetMask;
extern lv_obj_t *ui_ConfigLabelNetMask2;
extern lv_obj_t *ui_ConfigBtnMainDNS;
extern lv_obj_t *ui_ConfigLabelMainDNS2;
extern lv_obj_t *ui_ConfigBtnSubDNS;
extern lv_obj_t *ui_ConfigLabelSubDNS2;
extern lv_obj_t *ui_ConfigPanelForVersion;
extern lv_obj_t *ui_ConfigLabelAppUp1;
extern lv_obj_t *ui_ConfigDecoration4;
extern lv_obj_t *ui_ConfigPanelAppUp;
extern lv_obj_t *ui_ConfigLabelAppUp2;
extern lv_obj_t *ui_ConfigBtnReset;
extern lv_obj_t *ui_ConfigLabelReset;
extern lv_obj_t *ui_ConfigLabelAppUp3;
extern lv_obj_t *ui_ConfigPanelForAbout;
extern lv_obj_t *ui_ConfigLabelAppUp4;
extern lv_obj_t *ui_ConfigDecoration5;
extern lv_obj_t *ui_ConfirmBtnReset2;
extern lv_obj_t *ui_ConfirmLabelAppUp1;
extern lv_obj_t *ui_ConfigDecoration6;
extern lv_obj_t *ui_ConfigDecoration7;
extern lv_obj_t *ui_ConfigDecoration8;
extern lv_obj_t *ui_ConfigLabelIP1;
extern lv_obj_t *ui_ConfigLabelIP2;
extern lv_obj_t *ui_ConfigLabelSerialNum1;
extern lv_obj_t *ui_ConfigLabelSerialNum2;
extern lv_obj_t *ui_ConfigLabelLinuxVer1;
extern lv_obj_t *ui_ConfigLabelLinuxVer2;
extern lv_obj_t *ui_ConfigLabelManufacturer1;
extern lv_obj_t *ui_ConfigLabelManufacturer2;
extern lv_obj_t *ui_ConfigLabelSoftVer1;
extern lv_obj_t *ui_ConfigLabelSoftVer2;
extern lv_obj_t *ui_ConfigLabelHardwareVer1;
extern lv_obj_t *ui_ConfigLabelHardwareVer2;
extern lv_obj_t *ui_ConfigLabelKernelVer1;
extern lv_obj_t *ui_ConfigLabelKernelVer2;
extern lv_obj_t *ui_ConfigLabelH5Ver1;
extern lv_obj_t *ui_ConfigLabelH5Ver2;
extern lv_obj_t *ui_ConfigPanelForDevList1;
extern lv_obj_t *ui_ConfigLabelDevList2;
extern lv_obj_t *ui_ConfigBtnRefreshDevList;
extern lv_obj_t *ui_ConfigLabelRefreshDevList;
extern lv_obj_t *ui_ConfigDecoration9;
extern lv_obj_t *ui_ConfigPanelForDevList2;
extern lv_obj_t *ui_ConfigPanelDevMsg;
extern lv_obj_t *ui_ConfigLabelDevName;
extern lv_obj_t *ui_ConfigLabelDevState;
extern lv_obj_t *ui_ConfigLabelDevVer;
extern lv_obj_t *ui_ConfigLabelDevOperation;
extern lv_obj_t *ui_ConfigPanelDecoration10;
extern lv_obj_t *ui_TempPanel1;
extern lv_obj_t *ui_TempDecoration2;
extern lv_obj_t *ui_TempBtnManage1;
extern lv_obj_t *ui_TempLabelManage1;
extern lv_obj_t *ui_TempBtnUpdate1;
extern lv_obj_t *ui_TempLabelUpdate1;
extern lv_obj_t *ui_TempLabelDev1Name1;
extern lv_obj_t *ui_TempLabelDev1State1;
extern lv_obj_t *ui_TempLabelDev1Ver1;
extern lv_obj_t *ui_ConfigLabelNoSubDev;
extern lv_obj_t *ui_ConfigKeyboard;
// SCREEN: ui_ScreenVoiceSet
void ui_ScreenVoiceSet_screen_init(void);
extern lv_obj_t *ui_ScreenVoiceSet;
extern lv_obj_t *ui_VoicePanelTitle;
extern lv_obj_t *ui_VoiceBtnBack;
extern lv_obj_t *ui_VoiceLabelTime;
extern lv_obj_t *ui_VoiceDecoration;
extern lv_obj_t *ui_VoiceLabelSetting1;
extern lv_obj_t *ui_VoiceLabelSetting2;
extern lv_obj_t *ui_VoicePanel;
extern lv_obj_t *ui_VoiceSliderVolume;
extern lv_obj_t *ui_VoiceLabelVolume1;
extern lv_obj_t *ui_VoiceLabelVolume2;
extern lv_obj_t *ui_VoiceSliderTone;
extern lv_obj_t *ui_VoiceLabelTone1;
extern lv_obj_t *ui_VoiceLabelTone2;
extern lv_obj_t *ui_VoiceSliderPace;
extern lv_obj_t *ui_VoiceLabelPace1;
extern lv_obj_t *ui_VoiceLabelPace2;
// SCREEN: ui_ScreenRoomMain
void ui_ScreenRoomMain_screen_init(void);
extern lv_obj_t *ui_ScreenRoomMain;
extern lv_obj_t *ui_RoomMainPanelTtitle;
extern lv_obj_t *ui_RoomMainBtnBack;
extern lv_obj_t *ui_RoomMainLabelTime;
extern lv_obj_t *ui_RoomMainPanelSceneMode;
extern lv_obj_t *ui_RoomMainSceneModeLabel1;
extern lv_obj_t *ui_RoomMainBtnSceneMode;
extern lv_obj_t *ui_RoomMainSceneModeLabel3;
extern lv_obj_t *ui_RoomMainPanelAircon;
extern lv_obj_t *ui_RoomMainLabelAircon;
extern lv_obj_t *ui_RoomMainLabelTemp1;
extern lv_obj_t *ui_RoomMainLabelTemp2;
extern lv_obj_t *ui_RoomMainLabelAirconMode2;
extern lv_obj_t *ui_RoomMainLabelAirconMode1;
extern lv_obj_t *ui_RoomMainBtnAirconUp;
extern lv_obj_t *ui_RoomMainPanelAirconDown;
extern lv_obj_t *ui_RoomMainIconDegree;
extern lv_obj_t *ui_RoomMainBtnAirconMode;
extern lv_obj_t *ui_RoomMainBtnAirconWind;
extern lv_obj_t *ui_RoomMainBtnAirconDown;
extern lv_obj_t *ui_RoomMainBtnAirconSW;
extern lv_obj_t *ui_RoomMainLabelAirconSW;
extern lv_obj_t *ui_RoomMainPanelMainSw;
extern lv_obj_t *ui_RoomMainSw;
extern lv_obj_t *ui_RoomMainLabelSw;
extern lv_obj_t *ui_RoomMainPanelWindow;
extern lv_obj_t *ui_RoomMainLabelWindow;
extern lv_obj_t *ui_RoomMainIconWindow;
extern lv_obj_t *ui_RoomMainPanelLight;
extern lv_obj_t *ui_RoomMainIconLight;
extern lv_obj_t *ui_RoomMainLabelLight;
// SCREEN: ui_ScreenRoomWin
void ui_ScreenRoomWin_screen_init(void);
extern lv_obj_t *ui_ScreenRoomWin;
extern lv_obj_t *ui_RoomWinPanelTtitle;
extern lv_obj_t *ui_RoomWinBtnBack;
extern lv_obj_t *ui_RoomWinLabelTime;
extern lv_obj_t *ui_RoomWinPanelCtrl1;
extern lv_obj_t *ui_RoomWinPanelGauze;
extern lv_obj_t *ui_RoomWinLabelGauze;
extern lv_obj_t *ui_RoomWinIconGauze;
extern lv_obj_t *ui_RoomWinPanelCloth;
extern lv_obj_t *ui_RoomWinLabelCloth;
extern lv_obj_t *ui_RoomWinIconCloth;
extern lv_obj_t *ui_RoomWinLabel;
extern lv_obj_t *ui_RoomWinBtnOpen1;
extern lv_obj_t *ui_RoomWinBtnPause1;
extern lv_obj_t *ui_RoomWinBtnClose1;
extern lv_obj_t *ui_RoomWinPanelCtrl2;
extern lv_obj_t *ui_RoomWinBtnOpen2;
extern lv_obj_t *ui_RoomWinLabelOpen;
extern lv_obj_t *ui_RoomWinIconOpen;
extern lv_obj_t *ui_RoomWinBtnClose2;
extern lv_obj_t *ui_RoomWinLabelClose;
extern lv_obj_t *ui_RoomWinIconClose;
extern lv_obj_t *ui_RoomWinBtnBack1;
extern lv_obj_t *ui_RoomWinLabelBack;
// SCREEN: ui_ScreenRoomRelay
void ui_ScreenRoomRelay_screen_init(void);
extern lv_obj_t *ui_ScreenRoomRelay;
extern lv_obj_t *ui_RoomRelayPanelTtitle;
extern lv_obj_t *ui_RoomRelayBtnBack;
extern lv_obj_t *ui_RoomRelayLabelTime;
extern lv_obj_t *ui_RoomRelayBtnOpen4;
extern lv_obj_t *ui_RoomRelayLabelOpen1;
extern lv_obj_t *ui_RoomRelayIconOpen1;
extern lv_obj_t *ui_RoomRelayBtnBack1;
extern lv_obj_t *ui_RoomRelayLabelBack;
extern lv_obj_t *ui_RoomRelayBtnOpen3;
extern lv_obj_t *ui_RoomRelayLabelOpen2;
extern lv_obj_t *ui_RoomRelayIconOpen2;
extern lv_obj_t *ui_RoomRelayBtnRelay9;
extern lv_obj_t *ui_RoomRelayLabelRelay9;
extern lv_obj_t *ui_RoomRelaySwRelay9;
extern lv_obj_t *ui_RoomRelayBtnRelay11;
extern lv_obj_t *ui_RoomRelayLabelRelay11;
extern lv_obj_t *ui_RoomRelaySwRelay11;
extern lv_obj_t *ui_RoomRelayBtnRelay5;
extern lv_obj_t *ui_RoomRelayLabelRelay5;
extern lv_obj_t *ui_RoomRelaySwRelay5;
extern lv_obj_t *ui_RoomRelayBtnRelay10;
extern lv_obj_t *ui_RoomRelayLabelRelay10;
extern lv_obj_t *ui_RoomRelaySwRelay10;
extern lv_obj_t *ui_RoomRelayBtnRelay7;
extern lv_obj_t *ui_RoomRelayLabelRelay7;
extern lv_obj_t *ui_RoomRelaySwRelay7;
extern lv_obj_t *ui_RoomRelayBtnRelay8;
extern lv_obj_t *ui_RoomRelayLabelRelay8;
extern lv_obj_t *ui_RoomRelaySwRelay8;
extern lv_obj_t *ui_RoomRelayBtnRelay12;
extern lv_obj_t *ui_RoomRelayLabelRelay12;
extern lv_obj_t *ui_RoomRelaySwRelay12;
extern lv_obj_t *ui_RoomRelayBtnRelay13;
extern lv_obj_t *ui_RoomRelayLabelRelay13;
extern lv_obj_t *ui_RoomRelaySwRelay13;
// SCREEN: ui_ScreenDebug
void ui_ScreenDebug_screen_init(void);
extern lv_obj_t *ui_ScreenDebug;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Panel7;
// SCREEN: ui_ScreenMusic
void ui_ScreenMusic_screen_init(void);
extern lv_obj_t *ui_ScreenMusic;
extern lv_obj_t *ui_MusicPanelTtitle;
extern lv_obj_t *ui_MusicBtnBack;
extern lv_obj_t *ui_MusicLabelTime;
extern lv_obj_t *ui_MusicPanelMain;
extern lv_obj_t *ui_MusicBarMusicBar;
extern lv_obj_t *ui_MusicPanelMusicList;
extern lv_obj_t *ui_MusicPanelMusic1;
extern lv_obj_t *ui_MusicLabelMusic1;
extern lv_obj_t *ui_MusicBtnNext;
extern lv_obj_t *ui_MusicLabelNext;
extern lv_obj_t *ui_MusicBtnStart;
extern lv_obj_t *ui_MusicLabelStart;
extern lv_obj_t *ui_MusicBtnLast;
extern lv_obj_t *ui_MusicLabelLast;
extern lv_obj_t *ui_MusicBtnVoice;
extern lv_obj_t *ui_MusicLabelVoice;
extern lv_obj_t *ui_MusicPanelMusicNow;
extern lv_obj_t *ui_MusicLabelMusicNow;
extern lv_obj_t *ui_MusicBtnMode;
extern lv_obj_t *ui_MusicLabelMode;
extern lv_obj_t *ui_MusicLabelMusicBarLabel;
extern lv_obj_t *ui_MusicIcon1;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_main_png);   // assets\main.png
LV_IMG_DECLARE( ui_img_call_png);   // assets\call.png
LV_IMG_DECLARE( ui_img_setup_png);   // assets\setup.png
LV_IMG_DECLARE( ui_img_1769761639);   // assets\room-ctl.png
LV_IMG_DECLARE( ui_img_music_icon_png);   // assets\music_icon.png
LV_IMG_DECLARE( ui_img_1611405318);   // assets\返回.png
LV_IMG_DECLARE( ui_img_1215410760);   // assets\重启.png
LV_IMG_DECLARE( ui_img_1839223040);   // assets\初始化.png
LV_IMG_DECLARE( ui_img_1595275858);   // assets\设置48x48.png
LV_IMG_DECLARE( ui_img_ble_icon48x68_png);   // assets\Ble_Icon48x68.png
LV_IMG_DECLARE( ui_img_lora_icon64x64_png);   // assets\LoRa_Icon64x64.png
LV_IMG_DECLARE( ui_img_89075366);   // assets\设备列表64x64.png
LV_IMG_DECLARE( ui_img_1382371627);   // assets\+.png
LV_IMG_DECLARE( ui_img_1028724577);   // assets\-.png
LV_IMG_DECLARE( ui_img_767853082);   // assets\模式自动.png
LV_IMG_DECLARE( ui_img_122363411);   // assets\自动风速.png
LV_IMG_DECLARE( ui_img_725633117);   // assets\窗帘.png
LV_IMG_DECLARE( ui_img_1665777588);   // assets\灯光.png
LV_IMG_DECLARE( ui_img_763119327);   // assets\窗帘2.png
LV_IMG_DECLARE( ui_img_403254681);   // assets\窗帘开.png
LV_IMG_DECLARE( ui_img_930994846);   // assets\暂停.png
LV_IMG_DECLARE( ui_img_1844143814);   // assets\窗帘关.png
LV_IMG_DECLARE( ui_img_107693808);   // assets\调光.png
LV_IMG_DECLARE( ui_img_130793449);   // assets\调色.png
LV_IMG_DECLARE( ui_img_117415882);   // assets\中风速.png
LV_IMG_DECLARE( ui_img_575592273);   // assets\低风速.png
LV_IMG_DECLARE( ui_img_11555231);   // assets\高风速.png
LV_IMG_DECLARE( ui_img_1894006371);   // assets\模式制冷.png
LV_IMG_DECLARE( ui_img_1902601757);   // assets\模式制热.png
LV_IMG_DECLARE( ui_img_2107464944);   // assets\模式通风.png
LV_IMG_DECLARE( ui_img_1869319599);   // assets\模式除湿.png
LV_IMG_DECLARE( ui_img_music_playlist_sound_icon_png);   // assets\music_playlist_sound_icon.png

LV_FONT_DECLARE( ui_font_CN20);
LV_FONT_DECLARE( ui_font_CN24);
LV_FONT_DECLARE( ui_font_CN28);
LV_FONT_DECLARE( ui_font_CN32);
LV_FONT_DECLARE( ui_font_degreeCentigrade);
LV_FONT_DECLARE( ui_font_IconWiFI28);
LV_FONT_DECLARE( ui_font_Number128);
LV_FONT_DECLARE( ui_font_Switch48);
LV_FONT_DECLARE( ui_font_MusicIcon);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
