// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenMain_screen_init(void)
{
ui_ScreenMain = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_ScreenMain, &ui_img_main_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_MainBtnCall = lv_btn_create(ui_ScreenMain);
lv_obj_set_width( ui_MainBtnCall, 100);
lv_obj_set_height( ui_MainBtnCall, 140);
lv_obj_set_x( ui_MainBtnCall, 413 );
lv_obj_set_y( ui_MainBtnCall, 164 );
lv_obj_set_align( ui_MainBtnCall, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MainBtnCall, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MainBtnCall, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainBtnCall, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainBtnCall, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MainBtnCall, &ui_img_call_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_MainPanelSet = lv_obj_create(ui_ScreenMain);
lv_obj_set_width( ui_MainPanelSet, 150);
lv_obj_set_height( ui_MainPanelSet, 70);
lv_obj_set_x( ui_MainPanelSet, -430 );
lv_obj_set_y( ui_MainPanelSet, 260 );
lv_obj_set_align( ui_MainPanelSet, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_MainPanelSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainPanelSet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainPanelSet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MainPanelSet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainBtnSet = lv_btn_create(ui_MainPanelSet);
lv_obj_set_width( ui_MainBtnSet, 75);
lv_obj_set_height( ui_MainBtnSet, 60);
lv_obj_set_x( ui_MainBtnSet, -25 );
lv_obj_set_y( ui_MainBtnSet, 0 );
lv_obj_set_align( ui_MainBtnSet, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MainBtnSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MainBtnSet, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainBtnSet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainBtnSet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MainBtnSet, &ui_img_setup_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_MainLabelSet = lv_label_create(ui_MainPanelSet);
lv_obj_set_width( ui_MainLabelSet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainLabelSet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainLabelSet, 40 );
lv_obj_set_y( ui_MainLabelSet, 0 );
lv_obj_set_align( ui_MainLabelSet, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainLabelSet,"设置");
lv_obj_set_style_text_font(ui_MainLabelSet, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainPanelRoomCtrl = lv_obj_create(ui_ScreenMain);
lv_obj_set_width( ui_MainPanelRoomCtrl, 150);
lv_obj_set_height( ui_MainPanelRoomCtrl, 70);
lv_obj_set_x( ui_MainPanelRoomCtrl, -260 );
lv_obj_set_y( ui_MainPanelRoomCtrl, 260 );
lv_obj_set_align( ui_MainPanelRoomCtrl, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_MainPanelRoomCtrl, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainPanelRoomCtrl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainPanelRoomCtrl, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MainPanelRoomCtrl, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainBtnRoomCtrl = lv_btn_create(ui_MainPanelRoomCtrl);
lv_obj_set_width( ui_MainBtnRoomCtrl, 75);
lv_obj_set_height( ui_MainBtnRoomCtrl, 60);
lv_obj_set_x( ui_MainBtnRoomCtrl, -25 );
lv_obj_set_y( ui_MainBtnRoomCtrl, 0 );
lv_obj_set_align( ui_MainBtnRoomCtrl, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MainBtnRoomCtrl, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MainBtnRoomCtrl, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainBtnRoomCtrl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainBtnRoomCtrl, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MainBtnRoomCtrl, &ui_img_1769761639, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_MainLabelRoomCtrl = lv_label_create(ui_MainPanelRoomCtrl);
lv_obj_set_width( ui_MainLabelRoomCtrl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainLabelRoomCtrl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainLabelRoomCtrl, 40 );
lv_obj_set_y( ui_MainLabelRoomCtrl, 0 );
lv_obj_set_align( ui_MainLabelRoomCtrl, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainLabelRoomCtrl,"中控");
lv_obj_set_style_text_font(ui_MainLabelRoomCtrl, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainPanelMusic = lv_obj_create(ui_ScreenMain);
lv_obj_set_width( ui_MainPanelMusic, 150);
lv_obj_set_height( ui_MainPanelMusic, 70);
lv_obj_set_x( ui_MainPanelMusic, -90 );
lv_obj_set_y( ui_MainPanelMusic, 260 );
lv_obj_set_align( ui_MainPanelMusic, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_MainPanelMusic, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainPanelMusic, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainPanelMusic, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MainPanelMusic, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainBtnMusic = lv_btn_create(ui_MainPanelMusic);
lv_obj_set_width( ui_MainBtnMusic, 75);
lv_obj_set_height( ui_MainBtnMusic, 60);
lv_obj_set_x( ui_MainBtnMusic, -25 );
lv_obj_set_y( ui_MainBtnMusic, 0 );
lv_obj_set_align( ui_MainBtnMusic, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MainBtnMusic, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MainBtnMusic, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainBtnMusic, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainBtnMusic, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MainBtnMusic, &ui_img_music_icon_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_MainLabelMusic = lv_label_create(ui_MainPanelMusic);
lv_obj_set_width( ui_MainLabelMusic, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainLabelMusic, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainLabelMusic, 40 );
lv_obj_set_y( ui_MainLabelMusic, 0 );
lv_obj_set_align( ui_MainLabelMusic, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainLabelMusic,"音乐");
lv_obj_set_style_text_font(ui_MainLabelMusic, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainLabelDay = lv_label_create(ui_ScreenMain);
lv_obj_set_width( ui_MainLabelDay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainLabelDay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainLabelDay, 0 );
lv_obj_set_y( ui_MainLabelDay, -155 );
lv_obj_set_align( ui_MainLabelDay, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainLabelDay,"01月01日  Mon");
lv_obj_set_style_text_font(ui_MainLabelDay, &ui_font_CN32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainLabelMsg = lv_label_create(ui_ScreenMain);
lv_obj_set_width( ui_MainLabelMsg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainLabelMsg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainLabelMsg, 0 );
lv_obj_set_y( ui_MainLabelMsg, -270 );
lv_obj_set_align( ui_MainLabelMsg, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainLabelMsg,"索易智能中控台");
lv_obj_set_style_text_font(ui_MainLabelMsg, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainLabelErr = lv_label_create(ui_ScreenMain);
lv_obj_set_width( ui_MainLabelErr, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainLabelErr, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainLabelErr, -400 );
lv_obj_set_y( ui_MainLabelErr, -260 );
lv_obj_set_align( ui_MainLabelErr, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainLabelErr,"!设备未激活");
lv_obj_set_style_text_color(ui_MainLabelErr, lv_color_hex(0xE30000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainLabelErr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainLabelErr, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainLabelTime = lv_label_create(ui_ScreenMain);
lv_obj_set_width( ui_MainLabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainLabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainLabelTime, 0 );
lv_obj_set_y( ui_MainLabelTime, -70 );
lv_obj_set_align( ui_MainLabelTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainLabelTime,"00:00");
lv_obj_set_style_text_color(ui_MainLabelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainLabelTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainLabelTime, &ui_font_Number128, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainIconWiFi = lv_label_create(ui_ScreenMain);
lv_obj_set_width( ui_MainIconWiFi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainIconWiFi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainIconWiFi, -10 );
lv_obj_set_y( ui_MainIconWiFi, 10 );
lv_obj_set_align( ui_MainIconWiFi, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_MainIconWiFi,"有");
lv_obj_set_style_text_color(ui_MainIconWiFi, lv_color_hex(0xCDCDCD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainIconWiFi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainIconWiFi, &ui_font_IconWiFI28, LV_PART_MAIN| LV_STATE_DEFAULT);

}
