// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenDebug_screen_init(void)
{
ui_ScreenDebug = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenDebug, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_ScreenDebug);
lv_obj_set_width( ui_Panel1, 100);
lv_obj_set_height( ui_Panel1, 50);
lv_obj_set_x( ui_Panel1, -361 );
lv_obj_set_y( ui_Panel1, -122 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Panel1, &ui_img_117415882, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Panel2 = lv_obj_create(ui_ScreenDebug);
lv_obj_set_width( ui_Panel2, 100);
lv_obj_set_height( ui_Panel2, 50);
lv_obj_set_x( ui_Panel2, -362 );
lv_obj_set_y( ui_Panel2, -54 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Panel2, &ui_img_575592273, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Panel3 = lv_obj_create(ui_ScreenDebug);
lv_obj_set_width( ui_Panel3, 100);
lv_obj_set_height( ui_Panel3, 50);
lv_obj_set_x( ui_Panel3, -369 );
lv_obj_set_y( ui_Panel3, 11 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Panel3, &ui_img_11555231, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Panel4 = lv_obj_create(ui_ScreenDebug);
lv_obj_set_width( ui_Panel4, 100);
lv_obj_set_height( ui_Panel4, 50);
lv_obj_set_x( ui_Panel4, -247 );
lv_obj_set_y( ui_Panel4, -120 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Panel4, &ui_img_1894006371, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Panel5 = lv_obj_create(ui_ScreenDebug);
lv_obj_set_width( ui_Panel5, 100);
lv_obj_set_height( ui_Panel5, 50);
lv_obj_set_x( ui_Panel5, -247 );
lv_obj_set_y( ui_Panel5, -58 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Panel5, &ui_img_1902601757, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Panel6 = lv_obj_create(ui_ScreenDebug);
lv_obj_set_width( ui_Panel6, 100);
lv_obj_set_height( ui_Panel6, 50);
lv_obj_set_x( ui_Panel6, -252 );
lv_obj_set_y( ui_Panel6, 2 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Panel6, &ui_img_2107464944, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Panel7 = lv_obj_create(ui_ScreenDebug);
lv_obj_set_width( ui_Panel7, 100);
lv_obj_set_height( ui_Panel7, 50);
lv_obj_set_x( ui_Panel7, -246 );
lv_obj_set_y( ui_Panel7, 66 );
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Panel7, &ui_img_1869319599, LV_PART_MAIN | LV_STATE_DEFAULT );


}
