// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenRoomMain_screen_init(void)
{
ui_ScreenRoomMain = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenRoomMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenRoomMain, lv_color_hex(0x201E1C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenRoomMain, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenRoomMain, lv_color_hex(0x1E1B0E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenRoomMain, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainPanelTtitle = lv_obj_create(ui_ScreenRoomMain);
lv_obj_set_width( ui_RoomMainPanelTtitle, 1024);
lv_obj_set_height( ui_RoomMainPanelTtitle, 60);
lv_obj_clear_flag( ui_RoomMainPanelTtitle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomMainPanelTtitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomMainPanelTtitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainPanelTtitle, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomMainPanelTtitle, lv_color_hex(0x1C190C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomMainPanelTtitle, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomMainPanelTtitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomMainPanelTtitle, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomMainPanelTtitle, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainBtnBack = lv_btn_create(ui_RoomMainPanelTtitle);
lv_obj_set_width( ui_RoomMainBtnBack, 100);
lv_obj_set_height( ui_RoomMainBtnBack, 60);
lv_obj_set_x( ui_RoomMainBtnBack, -20 );
lv_obj_set_y( ui_RoomMainBtnBack, 0 );
lv_obj_set_align( ui_RoomMainBtnBack, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_RoomMainBtnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomMainBtnBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomMainBtnBack, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomMainBtnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainBtnBack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomMainBtnBack, &ui_img_1611405318, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RoomMainLabelTime = lv_label_create(ui_RoomMainPanelTtitle);
lv_obj_set_width( ui_RoomMainLabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomMainLabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RoomMainLabelTime, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_RoomMainLabelTime,"09:37");
lv_obj_set_style_text_font(ui_RoomMainLabelTime, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainPanelSceneMode = lv_obj_create(ui_ScreenRoomMain);
lv_obj_set_width( ui_RoomMainPanelSceneMode, 480);
lv_obj_set_height( ui_RoomMainPanelSceneMode, 480);
lv_obj_set_x( ui_RoomMainPanelSceneMode, 40 );
lv_obj_set_y( ui_RoomMainPanelSceneMode, 90 );
lv_obj_clear_flag( ui_RoomMainPanelSceneMode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomMainPanelSceneMode, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomMainPanelSceneMode, lv_color_hex(0x24211B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainPanelSceneMode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomMainPanelSceneMode, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainSceneModeLabel1 = lv_label_create(ui_RoomMainPanelSceneMode);
lv_obj_set_width( ui_RoomMainSceneModeLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomMainSceneModeLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomMainSceneModeLabel1, 0 );
lv_obj_set_y( ui_RoomMainSceneModeLabel1, 20 );
lv_label_set_text(ui_RoomMainSceneModeLabel1,"情景模式");
lv_obj_set_style_text_font(ui_RoomMainSceneModeLabel1, &ui_font_CN28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainBtnSceneMode = lv_label_create(ui_RoomMainPanelSceneMode);
lv_obj_set_width( ui_RoomMainBtnSceneMode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomMainBtnSceneMode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomMainBtnSceneMode, 0 );
lv_obj_set_y( ui_RoomMainBtnSceneMode, 20 );
lv_obj_set_align( ui_RoomMainBtnSceneMode, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_RoomMainBtnSceneMode,"更多模式>");
lv_obj_set_style_text_font(ui_RoomMainBtnSceneMode, &ui_font_CN28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainSceneModeLabel3 = lv_label_create(ui_RoomMainPanelSceneMode);
lv_obj_set_width( ui_RoomMainSceneModeLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomMainSceneModeLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomMainSceneModeLabel3, 0 );
lv_obj_set_y( ui_RoomMainSceneModeLabel3, 20 );
lv_obj_set_align( ui_RoomMainSceneModeLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomMainSceneModeLabel3,"请先设置情景模式!");
lv_obj_set_style_text_font(ui_RoomMainSceneModeLabel3, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainPanelAircon = lv_obj_create(ui_ScreenRoomMain);
lv_obj_set_width( ui_RoomMainPanelAircon, 430);
lv_obj_set_height( ui_RoomMainPanelAircon, 270);
lv_obj_set_x( ui_RoomMainPanelAircon, 560 );
lv_obj_set_y( ui_RoomMainPanelAircon, 300 );
lv_obj_clear_flag( ui_RoomMainPanelAircon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomMainPanelAircon, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomMainPanelAircon, lv_color_hex(0x24211B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainPanelAircon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomMainPanelAircon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainLabelAircon = lv_label_create(ui_RoomMainPanelAircon);
lv_obj_set_width( ui_RoomMainLabelAircon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomMainLabelAircon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomMainLabelAircon, 10 );
lv_obj_set_y( ui_RoomMainLabelAircon, 10 );
lv_label_set_text(ui_RoomMainLabelAircon,"空调");
lv_obj_set_style_text_font(ui_RoomMainLabelAircon, &ui_font_CN28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainLabelTemp1 = lv_label_create(ui_RoomMainPanelAircon);
lv_obj_set_width( ui_RoomMainLabelTemp1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomMainLabelTemp1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomMainLabelTemp1, 130 );
lv_obj_set_y( ui_RoomMainLabelTemp1, 50 );
lv_label_set_text(ui_RoomMainLabelTemp1,"2");
lv_obj_set_style_text_font(ui_RoomMainLabelTemp1, &ui_font_Number128, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainLabelTemp2 = lv_label_create(ui_RoomMainPanelAircon);
lv_obj_set_width( ui_RoomMainLabelTemp2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomMainLabelTemp2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomMainLabelTemp2, 200 );
lv_obj_set_y( ui_RoomMainLabelTemp2, 50 );
lv_label_set_text(ui_RoomMainLabelTemp2,"4");
lv_obj_set_style_text_font(ui_RoomMainLabelTemp2, &ui_font_Number128, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainLabelAirconMode2 = lv_label_create(ui_RoomMainPanelAircon);
lv_obj_set_width( ui_RoomMainLabelAirconMode2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomMainLabelAirconMode2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomMainLabelAirconMode2, 65 );
lv_obj_set_y( ui_RoomMainLabelAirconMode2, 110 );
lv_label_set_text(ui_RoomMainLabelAirconMode2,"模式");
lv_obj_set_style_text_font(ui_RoomMainLabelAirconMode2, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainLabelAirconMode1 = lv_label_create(ui_RoomMainPanelAircon);
lv_obj_set_width( ui_RoomMainLabelAirconMode1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomMainLabelAirconMode1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomMainLabelAirconMode1, 65 );
lv_obj_set_y( ui_RoomMainLabelAirconMode1, 50 );
lv_label_set_text(ui_RoomMainLabelAirconMode1,"制冷");
lv_obj_set_style_text_font(ui_RoomMainLabelAirconMode1, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainBtnAirconUp = lv_btn_create(ui_RoomMainPanelAircon);
lv_obj_set_width( ui_RoomMainBtnAirconUp, 70);
lv_obj_set_height( ui_RoomMainBtnAirconUp, 70);
lv_obj_set_x( ui_RoomMainBtnAirconUp, 15 );
lv_obj_set_y( ui_RoomMainBtnAirconUp, 160 );
lv_obj_add_flag( ui_RoomMainBtnAirconUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomMainBtnAirconUp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomMainBtnAirconUp, lv_color_hex(0xFBE8C9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainBtnAirconUp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomMainBtnAirconUp, lv_color_hex(0xE3B171), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomMainBtnAirconUp, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomMainBtnAirconUp, &ui_img_1382371627, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RoomMainPanelAirconDown = lv_obj_create(ui_RoomMainPanelAircon);
lv_obj_set_width( ui_RoomMainPanelAirconDown, 70);
lv_obj_set_height( ui_RoomMainPanelAirconDown, 70);
lv_obj_set_x( ui_RoomMainPanelAirconDown, 315 );
lv_obj_set_y( ui_RoomMainPanelAirconDown, 160 );
lv_obj_clear_flag( ui_RoomMainPanelAirconDown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomMainPanelAirconDown, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomMainPanelAirconDown, lv_color_hex(0xFBE8C9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainPanelAirconDown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomMainPanelAirconDown, lv_color_hex(0xE3B171), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomMainPanelAirconDown, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomMainPanelAirconDown, &ui_img_1028724577, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RoomMainIconDegree = lv_label_create(ui_RoomMainPanelAircon);
lv_obj_set_width( ui_RoomMainIconDegree, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomMainIconDegree, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomMainIconDegree, 261 );
lv_obj_set_y( ui_RoomMainIconDegree, 55 );
lv_label_set_text(ui_RoomMainIconDegree,"摄");
lv_obj_set_style_text_font(ui_RoomMainIconDegree, &ui_font_degreeCentigrade, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainBtnAirconMode = lv_btn_create(ui_RoomMainPanelAircon);
lv_obj_set_width( ui_RoomMainBtnAirconMode, 70);
lv_obj_set_height( ui_RoomMainBtnAirconMode, 70);
lv_obj_set_x( ui_RoomMainBtnAirconMode, 115 );
lv_obj_set_y( ui_RoomMainBtnAirconMode, 160 );
lv_obj_add_flag( ui_RoomMainBtnAirconMode, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomMainBtnAirconMode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomMainBtnAirconMode, lv_color_hex(0xFBE8C9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainBtnAirconMode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomMainBtnAirconMode, lv_color_hex(0xE3B171), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomMainBtnAirconMode, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomMainBtnAirconMode, &ui_img_767853082, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RoomMainBtnAirconWind = lv_btn_create(ui_RoomMainPanelAircon);
lv_obj_set_width( ui_RoomMainBtnAirconWind, 70);
lv_obj_set_height( ui_RoomMainBtnAirconWind, 70);
lv_obj_set_x( ui_RoomMainBtnAirconWind, 215 );
lv_obj_set_y( ui_RoomMainBtnAirconWind, 160 );
lv_obj_add_flag( ui_RoomMainBtnAirconWind, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomMainBtnAirconWind, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomMainBtnAirconWind, lv_color_hex(0xFBE8C9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainBtnAirconWind, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomMainBtnAirconWind, lv_color_hex(0xE3B171), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomMainBtnAirconWind, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomMainBtnAirconWind, &ui_img_122363411, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RoomMainBtnAirconDown = lv_btn_create(ui_RoomMainPanelAircon);
lv_obj_set_width( ui_RoomMainBtnAirconDown, 70);
lv_obj_set_height( ui_RoomMainBtnAirconDown, 70);
lv_obj_set_x( ui_RoomMainBtnAirconDown, 315 );
lv_obj_set_y( ui_RoomMainBtnAirconDown, 160 );
lv_obj_add_flag( ui_RoomMainBtnAirconDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomMainBtnAirconDown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomMainBtnAirconDown, lv_color_hex(0xFBE8C9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainBtnAirconDown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomMainBtnAirconDown, lv_color_hex(0xE3B171), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomMainBtnAirconDown, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomMainBtnAirconDown, &ui_img_1028724577, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RoomMainBtnAirconSW = lv_btn_create(ui_RoomMainPanelAircon);
lv_obj_set_width( ui_RoomMainBtnAirconSW, 55);
lv_obj_set_height( ui_RoomMainBtnAirconSW, 55);
lv_obj_set_x( ui_RoomMainBtnAirconSW, 320 );
lv_obj_set_y( ui_RoomMainBtnAirconSW, 0 );
lv_obj_add_flag( ui_RoomMainBtnAirconSW, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomMainBtnAirconSW, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomMainBtnAirconSW, lv_color_hex(0xFBE8C9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainBtnAirconSW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomMainBtnAirconSW, lv_color_hex(0xE3B171), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomMainBtnAirconSW, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainLabelAirconSW = lv_label_create(ui_RoomMainBtnAirconSW);
lv_obj_set_width( ui_RoomMainLabelAirconSW, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomMainLabelAirconSW, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RoomMainLabelAirconSW, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomMainLabelAirconSW,"开");
lv_obj_set_style_text_color(ui_RoomMainLabelAirconSW, lv_color_hex(0x614009), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RoomMainLabelAirconSW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RoomMainLabelAirconSW, &ui_font_Switch48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainPanelMainSw = lv_obj_create(ui_ScreenRoomMain);
lv_obj_set_width( ui_RoomMainPanelMainSw, 130);
lv_obj_set_height( ui_RoomMainPanelMainSw, 180);
lv_obj_set_x( ui_RoomMainPanelMainSw, 860 );
lv_obj_set_y( ui_RoomMainPanelMainSw, 90 );
lv_obj_clear_flag( ui_RoomMainPanelMainSw, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomMainPanelMainSw, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomMainPanelMainSw, lv_color_hex(0x24211B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainPanelMainSw, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomMainPanelMainSw, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainSw = lv_switch_create(ui_RoomMainPanelMainSw);
lv_obj_set_width( ui_RoomMainSw, 70);
lv_obj_set_height( ui_RoomMainSw, 30);
lv_obj_set_x( ui_RoomMainSw, 0 );
lv_obj_set_y( ui_RoomMainSw, -30 );
lv_obj_set_align( ui_RoomMainSw, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RoomMainSw, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_bg_color(ui_RoomMainSw, lv_color_hex(0xE0AE67), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_RoomMainSw, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_RoomMainLabelSw = lv_label_create(ui_RoomMainPanelMainSw);
lv_obj_set_width( ui_RoomMainLabelSw, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomMainLabelSw, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomMainLabelSw, 0 );
lv_obj_set_y( ui_RoomMainLabelSw, 40 );
lv_obj_set_align( ui_RoomMainLabelSw, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomMainLabelSw,"总开关");
lv_obj_set_style_text_font(ui_RoomMainLabelSw, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainPanelWindow = lv_obj_create(ui_ScreenRoomMain);
lv_obj_set_width( ui_RoomMainPanelWindow, 130);
lv_obj_set_height( ui_RoomMainPanelWindow, 180);
lv_obj_set_x( ui_RoomMainPanelWindow, 560 );
lv_obj_set_y( ui_RoomMainPanelWindow, 90 );
lv_obj_clear_flag( ui_RoomMainPanelWindow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomMainPanelWindow, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomMainPanelWindow, lv_color_hex(0x24211B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainPanelWindow, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomMainPanelWindow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainLabelWindow = lv_label_create(ui_RoomMainPanelWindow);
lv_obj_set_width( ui_RoomMainLabelWindow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomMainLabelWindow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomMainLabelWindow, 0 );
lv_obj_set_y( ui_RoomMainLabelWindow, 40 );
lv_obj_set_align( ui_RoomMainLabelWindow, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomMainLabelWindow,"窗帘");
lv_obj_set_style_text_font(ui_RoomMainLabelWindow, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainIconWindow = lv_obj_create(ui_RoomMainPanelWindow);
lv_obj_set_width( ui_RoomMainIconWindow, 100);
lv_obj_set_height( ui_RoomMainIconWindow, 150);
lv_obj_set_x( ui_RoomMainIconWindow, 0 );
lv_obj_set_y( ui_RoomMainIconWindow, -30 );
lv_obj_set_align( ui_RoomMainIconWindow, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RoomMainIconWindow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomMainIconWindow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainIconWindow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomMainIconWindow, &ui_img_725633117, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_width(ui_RoomMainIconWindow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainPanelLight = lv_obj_create(ui_ScreenRoomMain);
lv_obj_set_width( ui_RoomMainPanelLight, 130);
lv_obj_set_height( ui_RoomMainPanelLight, 180);
lv_obj_set_x( ui_RoomMainPanelLight, 710 );
lv_obj_set_y( ui_RoomMainPanelLight, 90 );
lv_obj_clear_flag( ui_RoomMainPanelLight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomMainPanelLight, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomMainPanelLight, lv_color_hex(0x24211B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainPanelLight, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomMainPanelLight, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainIconLight = lv_obj_create(ui_RoomMainPanelLight);
lv_obj_set_width( ui_RoomMainIconLight, 100);
lv_obj_set_height( ui_RoomMainIconLight, 150);
lv_obj_set_x( ui_RoomMainIconLight, 0 );
lv_obj_set_y( ui_RoomMainIconLight, -30 );
lv_obj_set_align( ui_RoomMainIconLight, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RoomMainIconLight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomMainIconLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomMainIconLight, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomMainIconLight, &ui_img_1665777588, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_width(ui_RoomMainIconLight, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomMainLabelLight = lv_label_create(ui_RoomMainPanelLight);
lv_obj_set_width( ui_RoomMainLabelLight, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomMainLabelLight, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomMainLabelLight, 0 );
lv_obj_set_y( ui_RoomMainLabelLight, 40 );
lv_obj_set_align( ui_RoomMainLabelLight, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomMainLabelLight,"灯光");
lv_obj_set_style_text_font(ui_RoomMainLabelLight, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
