// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenVoiceSet_screen_init(void)
{
ui_ScreenVoiceSet = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenVoiceSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenVoiceSet, lv_color_hex(0x201E1C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenVoiceSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenVoiceSet, lv_color_hex(0x1E1B0E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenVoiceSet, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ScreenVoiceSet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_width(ui_ScreenVoiceSet, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_VoicePanelTitle = lv_obj_create(ui_ScreenVoiceSet);
lv_obj_set_width( ui_VoicePanelTitle, 1024);
lv_obj_set_height( ui_VoicePanelTitle, 60);
lv_obj_clear_flag( ui_VoicePanelTitle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_VoicePanelTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_VoicePanelTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VoicePanelTitle, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_VoicePanelTitle, lv_color_hex(0x1C190C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_VoicePanelTitle, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_VoicePanelTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_VoicePanelTitle, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_VoicePanelTitle, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VoiceBtnBack = lv_btn_create(ui_VoicePanelTitle);
lv_obj_set_width( ui_VoiceBtnBack, 100);
lv_obj_set_height( ui_VoiceBtnBack, 60);
lv_obj_set_x( ui_VoiceBtnBack, -20 );
lv_obj_set_y( ui_VoiceBtnBack, 0 );
lv_obj_set_align( ui_VoiceBtnBack, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_VoiceBtnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_VoiceBtnBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_VoiceBtnBack, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_VoiceBtnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VoiceBtnBack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_VoiceBtnBack, &ui_img_1611405318, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_VoiceLabelTime = lv_label_create(ui_VoicePanelTitle);
lv_obj_set_width( ui_VoiceLabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoiceLabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VoiceLabelTime, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_VoiceLabelTime,"09:37");
lv_obj_set_style_text_font(ui_VoiceLabelTime, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VoiceDecoration = lv_obj_create(ui_ScreenVoiceSet);
lv_obj_set_width( ui_VoiceDecoration, 5);
lv_obj_set_height( ui_VoiceDecoration, 20);
lv_obj_set_x( ui_VoiceDecoration, 125 );
lv_obj_set_y( ui_VoiceDecoration, 125 );
lv_obj_clear_flag( ui_VoiceDecoration, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_VoiceDecoration, lv_color_hex(0xFFDBAE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VoiceDecoration, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_VoiceDecoration, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VoiceLabelSetting1 = lv_label_create(ui_ScreenVoiceSet);
lv_obj_set_width( ui_VoiceLabelSetting1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoiceLabelSetting1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoiceLabelSetting1, 140 );
lv_obj_set_y( ui_VoiceLabelSetting1, 122 );
lv_label_set_text(ui_VoiceLabelSetting1,"基础设置 >");
lv_obj_set_style_text_font(ui_VoiceLabelSetting1, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VoiceLabelSetting2 = lv_label_create(ui_ScreenVoiceSet);
lv_obj_set_width( ui_VoiceLabelSetting2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoiceLabelSetting2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoiceLabelSetting2, 270 );
lv_obj_set_y( ui_VoiceLabelSetting2, 122 );
lv_label_set_text(ui_VoiceLabelSetting2,"语音设置");
lv_obj_set_style_text_color(ui_VoiceLabelSetting2, lv_color_hex(0xFFAC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_VoiceLabelSetting2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_VoiceLabelSetting2, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VoicePanel = lv_obj_create(ui_ScreenVoiceSet);
lv_obj_set_width( ui_VoicePanel, 800);
lv_obj_set_height( ui_VoicePanel, 220);
lv_obj_set_align( ui_VoicePanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_VoicePanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_VoicePanel, lv_color_hex(0x14110B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VoicePanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_VoicePanel, lv_color_hex(0x675741), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_VoicePanel, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VoiceSliderVolume = lv_slider_create(ui_VoicePanel);
lv_obj_set_width( ui_VoiceSliderVolume, 400);
lv_obj_set_height( ui_VoiceSliderVolume, 7);
lv_obj_set_x( ui_VoiceSliderVolume, 160 );
lv_obj_set_y( ui_VoiceSliderVolume, 22 );
lv_obj_set_style_bg_color(ui_VoiceSliderVolume, lv_color_hex(0x706E6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VoiceSliderVolume, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VoiceSliderVolume, lv_color_hex(0xEEB567), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VoiceSliderVolume, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VoiceSliderVolume, lv_color_hex(0xF1B25C), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VoiceSliderVolume, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_VoiceSliderVolume, lv_color_hex(0xF09C40), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_VoiceSliderVolume, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_VoiceLabelVolume1 = lv_label_create(ui_VoicePanel);
lv_obj_set_width( ui_VoiceLabelVolume1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoiceLabelVolume1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoiceLabelVolume1, 50 );
lv_obj_set_y( ui_VoiceLabelVolume1, 10 );
lv_label_set_text(ui_VoiceLabelVolume1,"音量");
lv_obj_set_style_text_font(ui_VoiceLabelVolume1, &ui_font_CN28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VoiceLabelVolume2 = lv_label_create(ui_VoicePanel);
lv_obj_set_width( ui_VoiceLabelVolume2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoiceLabelVolume2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoiceLabelVolume2, 600 );
lv_obj_set_y( ui_VoiceLabelVolume2, 10 );
lv_label_set_text(ui_VoiceLabelVolume2,"0%");
lv_obj_set_style_text_font(ui_VoiceLabelVolume2, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VoiceSliderTone = lv_slider_create(ui_VoicePanel);
lv_obj_set_width( ui_VoiceSliderTone, 400);
lv_obj_set_height( ui_VoiceSliderTone, 7);
lv_obj_set_x( ui_VoiceSliderTone, 160 );
lv_obj_set_y( ui_VoiceSliderTone, 82 );
lv_obj_set_style_bg_color(ui_VoiceSliderTone, lv_color_hex(0x706E6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VoiceSliderTone, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VoiceSliderTone, lv_color_hex(0xEEB567), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VoiceSliderTone, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VoiceSliderTone, lv_color_hex(0xF1B25C), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VoiceSliderTone, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_VoiceSliderTone, lv_color_hex(0xF09C40), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_VoiceSliderTone, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_VoiceLabelTone1 = lv_label_create(ui_VoicePanel);
lv_obj_set_width( ui_VoiceLabelTone1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoiceLabelTone1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoiceLabelTone1, 50 );
lv_obj_set_y( ui_VoiceLabelTone1, 70 );
lv_label_set_text(ui_VoiceLabelTone1,"音调");
lv_obj_set_style_text_font(ui_VoiceLabelTone1, &ui_font_CN28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VoiceLabelTone2 = lv_label_create(ui_VoicePanel);
lv_obj_set_width( ui_VoiceLabelTone2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoiceLabelTone2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoiceLabelTone2, 600 );
lv_obj_set_y( ui_VoiceLabelTone2, 70 );
lv_label_set_text(ui_VoiceLabelTone2,"0%");
lv_obj_set_style_text_font(ui_VoiceLabelTone2, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VoiceSliderPace = lv_slider_create(ui_VoicePanel);
lv_obj_set_width( ui_VoiceSliderPace, 400);
lv_obj_set_height( ui_VoiceSliderPace, 7);
lv_obj_set_x( ui_VoiceSliderPace, 160 );
lv_obj_set_y( ui_VoiceSliderPace, 142 );
lv_obj_set_style_bg_color(ui_VoiceSliderPace, lv_color_hex(0x706E6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VoiceSliderPace, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VoiceSliderPace, lv_color_hex(0xEEB567), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VoiceSliderPace, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VoiceSliderPace, lv_color_hex(0xF1B25C), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VoiceSliderPace, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_VoiceSliderPace, lv_color_hex(0xF09C40), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_VoiceSliderPace, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_VoiceLabelPace1 = lv_label_create(ui_VoicePanel);
lv_obj_set_width( ui_VoiceLabelPace1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoiceLabelPace1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoiceLabelPace1, 50 );
lv_obj_set_y( ui_VoiceLabelPace1, 130 );
lv_label_set_text(ui_VoiceLabelPace1,"语速");
lv_obj_set_style_text_font(ui_VoiceLabelPace1, &ui_font_CN28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VoiceLabelPace2 = lv_label_create(ui_VoicePanel);
lv_obj_set_width( ui_VoiceLabelPace2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VoiceLabelPace2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_VoiceLabelPace2, 600 );
lv_obj_set_y( ui_VoiceLabelPace2, 130 );
lv_label_set_text(ui_VoiceLabelPace2,"0%");
lv_obj_set_style_text_font(ui_VoiceLabelPace2, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
