// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenRoomWin_screen_init(void)
{
ui_ScreenRoomWin = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenRoomWin, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenRoomWin, lv_color_hex(0x201E1C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenRoomWin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenRoomWin, lv_color_hex(0x1E1B0E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenRoomWin, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinPanelTtitle = lv_obj_create(ui_ScreenRoomWin);
lv_obj_set_width( ui_RoomWinPanelTtitle, 1024);
lv_obj_set_height( ui_RoomWinPanelTtitle, 60);
lv_obj_clear_flag( ui_RoomWinPanelTtitle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomWinPanelTtitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomWinPanelTtitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinPanelTtitle, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomWinPanelTtitle, lv_color_hex(0x1C190C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomWinPanelTtitle, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomWinPanelTtitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomWinPanelTtitle, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomWinPanelTtitle, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinBtnBack = lv_btn_create(ui_RoomWinPanelTtitle);
lv_obj_set_width( ui_RoomWinBtnBack, 100);
lv_obj_set_height( ui_RoomWinBtnBack, 60);
lv_obj_set_x( ui_RoomWinBtnBack, -20 );
lv_obj_set_y( ui_RoomWinBtnBack, 0 );
lv_obj_set_align( ui_RoomWinBtnBack, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_RoomWinBtnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomWinBtnBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomWinBtnBack, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomWinBtnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinBtnBack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomWinBtnBack, &ui_img_1611405318, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RoomWinLabelTime = lv_label_create(ui_RoomWinPanelTtitle);
lv_obj_set_width( ui_RoomWinLabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomWinLabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RoomWinLabelTime, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_RoomWinLabelTime,"09:37");
lv_obj_set_style_text_font(ui_RoomWinLabelTime, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinPanelCtrl1 = lv_obj_create(ui_ScreenRoomWin);
lv_obj_set_width( ui_RoomWinPanelCtrl1, 700);
lv_obj_set_height( ui_RoomWinPanelCtrl1, 480);
lv_obj_set_x( ui_RoomWinPanelCtrl1, 40 );
lv_obj_set_y( ui_RoomWinPanelCtrl1, 90 );
lv_obj_clear_flag( ui_RoomWinPanelCtrl1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomWinPanelCtrl1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomWinPanelCtrl1, lv_color_hex(0x24211B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinPanelCtrl1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomWinPanelCtrl1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinPanelGauze = lv_btn_create(ui_RoomWinPanelCtrl1);
lv_obj_set_width( ui_RoomWinPanelGauze, 250);
lv_obj_set_height( ui_RoomWinPanelGauze, 160);
lv_obj_set_x( ui_RoomWinPanelGauze, -160 );
lv_obj_set_y( ui_RoomWinPanelGauze, -50 );
lv_obj_set_align( ui_RoomWinPanelGauze, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoomWinPanelGauze, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomWinPanelGauze, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomWinPanelGauze, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinPanelGauze, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomWinPanelGauze, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomWinPanelGauze, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomWinPanelGauze, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomWinPanelGauze, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomWinPanelGauze, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinLabelGauze = lv_label_create(ui_RoomWinPanelGauze);
lv_obj_set_width( ui_RoomWinLabelGauze, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomWinLabelGauze, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomWinLabelGauze, 50 );
lv_obj_set_y( ui_RoomWinLabelGauze, 0 );
lv_obj_set_align( ui_RoomWinLabelGauze, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomWinLabelGauze,"纱帘");
lv_obj_set_style_text_font(ui_RoomWinLabelGauze, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinIconGauze = lv_btn_create(ui_RoomWinPanelGauze);
lv_obj_set_width( ui_RoomWinIconGauze, 80);
lv_obj_set_height( ui_RoomWinIconGauze, 80);
lv_obj_set_x( ui_RoomWinIconGauze, -40 );
lv_obj_set_y( ui_RoomWinIconGauze, 0 );
lv_obj_set_align( ui_RoomWinIconGauze, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoomWinIconGauze, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomWinIconGauze, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomWinIconGauze, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinIconGauze, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomWinIconGauze, &ui_img_763119327, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RoomWinPanelCloth = lv_btn_create(ui_RoomWinPanelCtrl1);
lv_obj_set_width( ui_RoomWinPanelCloth, 250);
lv_obj_set_height( ui_RoomWinPanelCloth, 160);
lv_obj_set_x( ui_RoomWinPanelCloth, 160 );
lv_obj_set_y( ui_RoomWinPanelCloth, -50 );
lv_obj_set_align( ui_RoomWinPanelCloth, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoomWinPanelCloth, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomWinPanelCloth, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomWinPanelCloth, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinPanelCloth, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomWinPanelCloth, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomWinPanelCloth, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomWinPanelCloth, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomWinPanelCloth, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomWinPanelCloth, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinLabelCloth = lv_label_create(ui_RoomWinPanelCloth);
lv_obj_set_width( ui_RoomWinLabelCloth, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomWinLabelCloth, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomWinLabelCloth, 50 );
lv_obj_set_y( ui_RoomWinLabelCloth, 0 );
lv_obj_set_align( ui_RoomWinLabelCloth, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomWinLabelCloth,"布帘");
lv_obj_set_style_text_font(ui_RoomWinLabelCloth, &ui_font_CN20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinIconCloth = lv_btn_create(ui_RoomWinPanelCloth);
lv_obj_set_width( ui_RoomWinIconCloth, 80);
lv_obj_set_height( ui_RoomWinIconCloth, 80);
lv_obj_set_x( ui_RoomWinIconCloth, -40 );
lv_obj_set_y( ui_RoomWinIconCloth, 0 );
lv_obj_set_align( ui_RoomWinIconCloth, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoomWinIconCloth, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomWinIconCloth, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomWinIconCloth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinIconCloth, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomWinIconCloth, &ui_img_725633117, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RoomWinLabel = lv_label_create(ui_RoomWinPanelCtrl1);
lv_obj_set_width( ui_RoomWinLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomWinLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomWinLabel, 0 );
lv_obj_set_y( ui_RoomWinLabel, 10 );
lv_label_set_text(ui_RoomWinLabel,"窗帘");
lv_obj_set_style_text_font(ui_RoomWinLabel, &ui_font_CN28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinBtnOpen1 = lv_btn_create(ui_RoomWinPanelCtrl1);
lv_obj_set_width( ui_RoomWinBtnOpen1, 100);
lv_obj_set_height( ui_RoomWinBtnOpen1, 100);
lv_obj_set_x( ui_RoomWinBtnOpen1, -170 );
lv_obj_set_y( ui_RoomWinBtnOpen1, 130 );
lv_obj_set_align( ui_RoomWinBtnOpen1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoomWinBtnOpen1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomWinBtnOpen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomWinBtnOpen1, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomWinBtnOpen1, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinBtnOpen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomWinBtnOpen1, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomWinBtnOpen1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomWinBtnOpen1, &ui_img_403254681, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_RoomWinBtnOpen1, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomWinBtnOpen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomWinBtnOpen1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinBtnPause1 = lv_btn_create(ui_RoomWinPanelCtrl1);
lv_obj_set_width( ui_RoomWinBtnPause1, 100);
lv_obj_set_height( ui_RoomWinBtnPause1, 100);
lv_obj_set_x( ui_RoomWinBtnPause1, 0 );
lv_obj_set_y( ui_RoomWinBtnPause1, 130 );
lv_obj_set_align( ui_RoomWinBtnPause1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoomWinBtnPause1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomWinBtnPause1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomWinBtnPause1, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomWinBtnPause1, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinBtnPause1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomWinBtnPause1, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomWinBtnPause1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomWinBtnPause1, &ui_img_930994846, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_RoomWinBtnPause1, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomWinBtnPause1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomWinBtnPause1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinBtnClose1 = lv_btn_create(ui_RoomWinPanelCtrl1);
lv_obj_set_width( ui_RoomWinBtnClose1, 100);
lv_obj_set_height( ui_RoomWinBtnClose1, 100);
lv_obj_set_x( ui_RoomWinBtnClose1, 170 );
lv_obj_set_y( ui_RoomWinBtnClose1, 130 );
lv_obj_set_align( ui_RoomWinBtnClose1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoomWinBtnClose1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomWinBtnClose1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomWinBtnClose1, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomWinBtnClose1, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinBtnClose1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomWinBtnClose1, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomWinBtnClose1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomWinBtnClose1, &ui_img_1844143814, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_RoomWinBtnClose1, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomWinBtnClose1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomWinBtnClose1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinPanelCtrl2 = lv_obj_create(ui_ScreenRoomWin);
lv_obj_set_width( ui_RoomWinPanelCtrl2, 180);
lv_obj_set_height( ui_RoomWinPanelCtrl2, 320);
lv_obj_set_x( ui_RoomWinPanelCtrl2, 790 );
lv_obj_set_y( ui_RoomWinPanelCtrl2, 90 );
lv_obj_clear_flag( ui_RoomWinPanelCtrl2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomWinPanelCtrl2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomWinPanelCtrl2, lv_color_hex(0x24211B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinPanelCtrl2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomWinPanelCtrl2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinBtnOpen2 = lv_btn_create(ui_RoomWinPanelCtrl2);
lv_obj_set_width( ui_RoomWinBtnOpen2, 110);
lv_obj_set_height( ui_RoomWinBtnOpen2, 120);
lv_obj_set_x( ui_RoomWinBtnOpen2, 0 );
lv_obj_set_y( ui_RoomWinBtnOpen2, -70 );
lv_obj_set_align( ui_RoomWinBtnOpen2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoomWinBtnOpen2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomWinBtnOpen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomWinBtnOpen2, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinBtnOpen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomWinBtnOpen2, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomWinBtnOpen2, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomWinBtnOpen2, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomWinBtnOpen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomWinBtnOpen2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinLabelOpen = lv_label_create(ui_RoomWinBtnOpen2);
lv_obj_set_width( ui_RoomWinLabelOpen, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomWinLabelOpen, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomWinLabelOpen, 0 );
lv_obj_set_y( ui_RoomWinLabelOpen, 30 );
lv_obj_set_align( ui_RoomWinLabelOpen, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomWinLabelOpen,"一键全开");
lv_obj_set_style_text_font(ui_RoomWinLabelOpen, &ui_font_CN20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinIconOpen = lv_btn_create(ui_RoomWinBtnOpen2);
lv_obj_set_width( ui_RoomWinIconOpen, 80);
lv_obj_set_height( ui_RoomWinIconOpen, 80);
lv_obj_set_x( ui_RoomWinIconOpen, 0 );
lv_obj_set_y( ui_RoomWinIconOpen, -15 );
lv_obj_set_align( ui_RoomWinIconOpen, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoomWinIconOpen, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomWinIconOpen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomWinIconOpen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinIconOpen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomWinIconOpen, &ui_img_403254681, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RoomWinBtnClose2 = lv_btn_create(ui_RoomWinPanelCtrl2);
lv_obj_set_width( ui_RoomWinBtnClose2, 110);
lv_obj_set_height( ui_RoomWinBtnClose2, 120);
lv_obj_set_x( ui_RoomWinBtnClose2, 0 );
lv_obj_set_y( ui_RoomWinBtnClose2, 80 );
lv_obj_set_align( ui_RoomWinBtnClose2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoomWinBtnClose2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomWinBtnClose2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomWinBtnClose2, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinBtnClose2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomWinBtnClose2, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomWinBtnClose2, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomWinBtnClose2, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomWinBtnClose2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomWinBtnClose2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinLabelClose = lv_label_create(ui_RoomWinBtnClose2);
lv_obj_set_width( ui_RoomWinLabelClose, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomWinLabelClose, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomWinLabelClose, 0 );
lv_obj_set_y( ui_RoomWinLabelClose, 30 );
lv_obj_set_align( ui_RoomWinLabelClose, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomWinLabelClose,"一键全关");
lv_obj_set_style_text_font(ui_RoomWinLabelClose, &ui_font_CN20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinIconClose = lv_btn_create(ui_RoomWinBtnClose2);
lv_obj_set_width( ui_RoomWinIconClose, 80);
lv_obj_set_height( ui_RoomWinIconClose, 80);
lv_obj_set_x( ui_RoomWinIconClose, 0 );
lv_obj_set_y( ui_RoomWinIconClose, -15 );
lv_obj_set_align( ui_RoomWinIconClose, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoomWinIconClose, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomWinIconClose, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomWinIconClose, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinIconClose, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomWinIconClose, &ui_img_1844143814, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RoomWinBtnBack1 = lv_btn_create(ui_ScreenRoomWin);
lv_obj_set_width( ui_RoomWinBtnBack1, 160);
lv_obj_set_height( ui_RoomWinBtnBack1, 100);
lv_obj_set_x( ui_RoomWinBtnBack1, 800 );
lv_obj_set_y( ui_RoomWinBtnBack1, 446 );
lv_obj_add_flag( ui_RoomWinBtnBack1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomWinBtnBack1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomWinBtnBack1, lv_color_hex(0xFBE8C9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomWinBtnBack1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomWinBtnBack1, lv_color_hex(0xE3B171), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomWinBtnBack1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomWinLabelBack = lv_label_create(ui_RoomWinBtnBack1);
lv_obj_set_width( ui_RoomWinLabelBack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomWinLabelBack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RoomWinLabelBack, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomWinLabelBack,"返回");
lv_obj_set_style_text_color(ui_RoomWinLabelBack, lv_color_hex(0x4C3911), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RoomWinLabelBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RoomWinLabelBack, &ui_font_CN32, LV_PART_MAIN| LV_STATE_DEFAULT);

}
