// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenMusic_screen_init(void)
{
ui_ScreenMusic = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenMusic, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenMusic, lv_color_hex(0x201E1C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMusic, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenMusic, lv_color_hex(0x1E1B0E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenMusic, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicPanelTtitle = lv_obj_create(ui_ScreenMusic);
lv_obj_set_width( ui_MusicPanelTtitle, 1024);
lv_obj_set_height( ui_MusicPanelTtitle, 60);
lv_obj_clear_flag( ui_MusicPanelTtitle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MusicPanelTtitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MusicPanelTtitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicPanelTtitle, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_MusicPanelTtitle, lv_color_hex(0x1C190C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_MusicPanelTtitle, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MusicPanelTtitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MusicPanelTtitle, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MusicPanelTtitle, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicBtnBack = lv_btn_create(ui_MusicPanelTtitle);
lv_obj_set_width( ui_MusicBtnBack, 100);
lv_obj_set_height( ui_MusicBtnBack, 60);
lv_obj_set_x( ui_MusicBtnBack, -20 );
lv_obj_set_y( ui_MusicBtnBack, 0 );
lv_obj_set_align( ui_MusicBtnBack, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_MusicBtnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MusicBtnBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MusicBtnBack, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MusicBtnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicBtnBack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MusicBtnBack, &ui_img_1611405318, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_MusicLabelTime = lv_label_create(ui_MusicPanelTtitle);
lv_obj_set_width( ui_MusicLabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MusicLabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MusicLabelTime, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_MusicLabelTime,"09:37");
lv_obj_set_style_text_font(ui_MusicLabelTime, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicPanelMain = lv_obj_create(ui_ScreenMusic);
lv_obj_set_width( ui_MusicPanelMain, 900);
lv_obj_set_height( ui_MusicPanelMain, 480);
lv_obj_set_x( ui_MusicPanelMain, 60 );
lv_obj_set_y( ui_MusicPanelMain, 90 );
lv_obj_clear_flag( ui_MusicPanelMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MusicPanelMain, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MusicPanelMain, lv_color_hex(0x181914), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicPanelMain, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_MusicPanelMain, lv_color_hex(0x454031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_MusicPanelMain, 180, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_MusicPanelMain, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_MusicPanelMain, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MusicPanelMain, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicBarMusicBar = lv_slider_create(ui_MusicPanelMain);
lv_slider_set_value( ui_MusicBarMusicBar, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_MusicBarMusicBar)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_MusicBarMusicBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_MusicBarMusicBar, 800);
lv_obj_set_height( ui_MusicBarMusicBar, 3);
lv_obj_set_x( ui_MusicBarMusicBar, 0 );
lv_obj_set_y( ui_MusicBarMusicBar, 130 );
lv_obj_set_align( ui_MusicBarMusicBar, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_MusicBarMusicBar, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MusicBarMusicBar, lv_color_hex(0x9C732E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicBarMusicBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_MusicBarMusicBar, lv_color_hex(0xFFBA43), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicBarMusicBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_MusicBarMusicBar, lv_color_hex(0xFFBA43), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicBarMusicBar, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_MusicPanelMusicList = lv_obj_create(ui_MusicPanelMain);
lv_obj_set_width( ui_MusicPanelMusicList, 900);
lv_obj_set_height( ui_MusicPanelMusicList, 350);
lv_obj_set_x( ui_MusicPanelMusicList, 0 );
lv_obj_set_y( ui_MusicPanelMusicList, -20 );
lv_obj_set_align( ui_MusicPanelMusicList, LV_ALIGN_TOP_MID );
lv_obj_set_scroll_dir(ui_MusicPanelMusicList, LV_DIR_VER);
lv_obj_set_style_bg_color(ui_MusicPanelMusicList, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicPanelMusicList, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MusicPanelMusicList, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicPanelMusic1 = lv_obj_create(ui_MusicPanelMusicList);
lv_obj_set_width( ui_MusicPanelMusic1, 380);
lv_obj_set_height( ui_MusicPanelMusic1, 70);
lv_obj_set_x( ui_MusicPanelMusic1, 20 );
lv_obj_set_y( ui_MusicPanelMusic1, 0 );
lv_obj_add_flag( ui_MusicPanelMusic1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_MusicPanelMusic1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MusicPanelMusic1, lv_color_hex(0x2A2D2C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicPanelMusic1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MusicPanelMusic1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicLabelMusic1 = lv_label_create(ui_MusicPanelMusic1);
lv_obj_set_width( ui_MusicLabelMusic1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MusicLabelMusic1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MusicLabelMusic1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_MusicLabelMusic1,"平凡之路");
lv_obj_set_style_text_font(ui_MusicLabelMusic1, &ui_font_CN28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicBtnNext = lv_btn_create(ui_MusicPanelMain);
lv_obj_set_width( ui_MusicBtnNext, 60);
lv_obj_set_height( ui_MusicBtnNext, 60);
lv_obj_set_x( ui_MusicBtnNext, 100 );
lv_obj_set_y( ui_MusicBtnNext, 185 );
lv_obj_set_align( ui_MusicBtnNext, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MusicBtnNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MusicBtnNext, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MusicBtnNext, lv_color_hex(0xF8E2BD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicBtnNext, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicLabelNext = lv_label_create(ui_MusicBtnNext);
lv_obj_set_width( ui_MusicLabelNext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MusicLabelNext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MusicLabelNext, LV_ALIGN_CENTER );
lv_label_set_text(ui_MusicLabelNext,"后");
lv_obj_set_style_text_color(ui_MusicLabelNext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MusicLabelNext, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MusicLabelNext, &ui_font_MusicIcon, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicBtnStart = lv_btn_create(ui_MusicPanelMain);
lv_obj_set_width( ui_MusicBtnStart, 60);
lv_obj_set_height( ui_MusicBtnStart, 60);
lv_obj_set_x( ui_MusicBtnStart, 0 );
lv_obj_set_y( ui_MusicBtnStart, 185 );
lv_obj_set_align( ui_MusicBtnStart, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MusicBtnStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MusicBtnStart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MusicBtnStart, 70, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MusicBtnStart, lv_color_hex(0xF8E2BD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicBtnStart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_MusicBtnStart, lv_color_hex(0xE6B779), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_MusicBtnStart, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicLabelStart = lv_label_create(ui_MusicBtnStart);
lv_obj_set_width( ui_MusicLabelStart, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MusicLabelStart, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MusicLabelStart, LV_ALIGN_CENTER );
lv_label_set_text(ui_MusicLabelStart,"播");
lv_obj_set_style_text_color(ui_MusicLabelStart, lv_color_hex(0x522900), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MusicLabelStart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MusicLabelStart, &ui_font_MusicIcon, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicBtnLast = lv_btn_create(ui_MusicPanelMain);
lv_obj_set_width( ui_MusicBtnLast, 60);
lv_obj_set_height( ui_MusicBtnLast, 60);
lv_obj_set_x( ui_MusicBtnLast, -100 );
lv_obj_set_y( ui_MusicBtnLast, 185 );
lv_obj_set_align( ui_MusicBtnLast, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MusicBtnLast, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MusicBtnLast, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MusicBtnLast, lv_color_hex(0xF8E2BD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicBtnLast, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicLabelLast = lv_label_create(ui_MusicBtnLast);
lv_obj_set_width( ui_MusicLabelLast, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MusicLabelLast, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MusicLabelLast, LV_ALIGN_CENTER );
lv_label_set_text(ui_MusicLabelLast,"前");
lv_obj_set_style_text_color(ui_MusicLabelLast, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MusicLabelLast, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MusicLabelLast, &ui_font_MusicIcon, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicBtnVoice = lv_btn_create(ui_MusicPanelMain);
lv_obj_set_width( ui_MusicBtnVoice, 60);
lv_obj_set_height( ui_MusicBtnVoice, 60);
lv_obj_set_x( ui_MusicBtnVoice, -170 );
lv_obj_set_y( ui_MusicBtnVoice, 185 );
lv_obj_set_align( ui_MusicBtnVoice, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MusicBtnVoice, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MusicBtnVoice, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MusicBtnVoice, lv_color_hex(0xF8E2BD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicBtnVoice, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicLabelVoice = lv_label_create(ui_MusicBtnVoice);
lv_obj_set_width( ui_MusicLabelVoice, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MusicLabelVoice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MusicLabelVoice, LV_ALIGN_CENTER );
lv_label_set_text(ui_MusicLabelVoice,"量");
lv_obj_set_style_text_color(ui_MusicLabelVoice, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MusicLabelVoice, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MusicLabelVoice, &ui_font_MusicIcon, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicPanelMusicNow = lv_obj_create(ui_MusicPanelMain);
lv_obj_set_width( ui_MusicPanelMusicNow, 200);
lv_obj_set_height( ui_MusicPanelMusicNow, 70);
lv_obj_set_x( ui_MusicPanelMusicNow, -260 );
lv_obj_set_y( ui_MusicPanelMusicNow, 185 );
lv_obj_set_align( ui_MusicPanelMusicNow, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_MusicPanelMusicNow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MusicPanelMusicNow, lv_color_hex(0x2A2D2C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicPanelMusicNow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MusicPanelMusicNow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicLabelMusicNow = lv_label_create(ui_MusicPanelMusicNow);
lv_obj_set_width( ui_MusicLabelMusicNow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MusicLabelMusicNow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MusicLabelMusicNow, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_MusicLabelMusicNow,"");
lv_obj_set_style_text_font(ui_MusicLabelMusicNow, &ui_font_CN28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicBtnMode = lv_btn_create(ui_MusicPanelMain);
lv_obj_set_width( ui_MusicBtnMode, 60);
lv_obj_set_height( ui_MusicBtnMode, 60);
lv_obj_set_x( ui_MusicBtnMode, 170 );
lv_obj_set_y( ui_MusicBtnMode, 185 );
lv_obj_set_align( ui_MusicBtnMode, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MusicBtnMode, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MusicBtnMode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MusicBtnMode, lv_color_hex(0xF8E2BD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicBtnMode, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicLabelMode = lv_label_create(ui_MusicBtnMode);
lv_obj_set_width( ui_MusicLabelMode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MusicLabelMode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MusicLabelMode, LV_ALIGN_CENTER );
lv_label_set_text(ui_MusicLabelMode,"列");
lv_obj_set_style_text_color(ui_MusicLabelMode, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MusicLabelMode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MusicLabelMode, &ui_font_MusicIcon, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicLabelMusicBarLabel = lv_label_create(ui_MusicPanelMain);
lv_obj_set_width( ui_MusicLabelMusicBarLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MusicLabelMusicBarLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MusicLabelMusicBarLabel, 382 );
lv_obj_set_y( ui_MusicLabelMusicBarLabel, 148 );
lv_obj_set_align( ui_MusicLabelMusicBarLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_MusicLabelMusicBarLabel,"3:40");

ui_MusicIcon1 = lv_obj_create(ui_MusicPanelMain);
lv_obj_set_width( ui_MusicIcon1, 50);
lv_obj_set_height( ui_MusicIcon1, 50);
lv_obj_set_x( ui_MusicIcon1, -390 );
lv_obj_set_y( ui_MusicIcon1, 185 );
lv_obj_set_align( ui_MusicIcon1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_MusicIcon1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MusicIcon1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MusicIcon1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MusicIcon1, &ui_img_music_playlist_sound_icon_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_width(ui_MusicIcon1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);


}
