// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenRoomRelay_screen_init(void)
{
ui_ScreenRoomRelay = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenRoomRelay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenRoomRelay, lv_color_hex(0x201E1C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenRoomRelay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ScreenRoomRelay, lv_color_hex(0x1E1B0E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ScreenRoomRelay, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayPanelTtitle = lv_obj_create(ui_ScreenRoomRelay);
lv_obj_set_width( ui_RoomRelayPanelTtitle, 1024);
lv_obj_set_height( ui_RoomRelayPanelTtitle, 60);
lv_obj_clear_flag( ui_RoomRelayPanelTtitle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomRelayPanelTtitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomRelayPanelTtitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayPanelTtitle, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomRelayPanelTtitle, lv_color_hex(0x1C190C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomRelayPanelTtitle, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomRelayPanelTtitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomRelayPanelTtitle, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomRelayPanelTtitle, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayBtnBack = lv_btn_create(ui_RoomRelayPanelTtitle);
lv_obj_set_width( ui_RoomRelayBtnBack, 100);
lv_obj_set_height( ui_RoomRelayBtnBack, 60);
lv_obj_set_x( ui_RoomRelayBtnBack, -20 );
lv_obj_set_y( ui_RoomRelayBtnBack, 0 );
lv_obj_set_align( ui_RoomRelayBtnBack, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_RoomRelayBtnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomRelayBtnBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RoomRelayBtnBack, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomRelayBtnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayBtnBack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomRelayBtnBack, &ui_img_1611405318, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RoomRelayLabelTime = lv_label_create(ui_RoomRelayPanelTtitle);
lv_obj_set_width( ui_RoomRelayLabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomRelayLabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RoomRelayLabelTime, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_RoomRelayLabelTime,"09:37");
lv_obj_set_style_text_font(ui_RoomRelayLabelTime, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayBtnOpen4 = lv_btn_create(ui_ScreenRoomRelay);
lv_obj_set_width( ui_RoomRelayBtnOpen4, 160);
lv_obj_set_height( ui_RoomRelayBtnOpen4, 150);
lv_obj_set_x( ui_RoomRelayBtnOpen4, 800 );
lv_obj_set_y( ui_RoomRelayBtnOpen4, 100 );
lv_obj_add_flag( ui_RoomRelayBtnOpen4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomRelayBtnOpen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomRelayBtnOpen4, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayBtnOpen4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomRelayBtnOpen4, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomRelayBtnOpen4, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomRelayBtnOpen4, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomRelayBtnOpen4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomRelayBtnOpen4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayLabelOpen1 = lv_label_create(ui_RoomRelayBtnOpen4);
lv_obj_set_width( ui_RoomRelayLabelOpen1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomRelayLabelOpen1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomRelayLabelOpen1, 0 );
lv_obj_set_y( ui_RoomRelayLabelOpen1, 45 );
lv_obj_set_align( ui_RoomRelayLabelOpen1, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomRelayLabelOpen1,"调光");
lv_obj_set_style_text_font(ui_RoomRelayLabelOpen1, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayIconOpen1 = lv_btn_create(ui_RoomRelayBtnOpen4);
lv_obj_set_width( ui_RoomRelayIconOpen1, 80);
lv_obj_set_height( ui_RoomRelayIconOpen1, 80);
lv_obj_set_x( ui_RoomRelayIconOpen1, 0 );
lv_obj_set_y( ui_RoomRelayIconOpen1, -15 );
lv_obj_set_align( ui_RoomRelayIconOpen1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoomRelayIconOpen1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomRelayIconOpen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomRelayIconOpen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayIconOpen1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomRelayIconOpen1, &ui_img_107693808, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RoomRelayBtnBack1 = lv_btn_create(ui_ScreenRoomRelay);
lv_obj_set_width( ui_RoomRelayBtnBack1, 160);
lv_obj_set_height( ui_RoomRelayBtnBack1, 100);
lv_obj_set_x( ui_RoomRelayBtnBack1, 800 );
lv_obj_set_y( ui_RoomRelayBtnBack1, 450 );
lv_obj_add_flag( ui_RoomRelayBtnBack1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomRelayBtnBack1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomRelayBtnBack1, lv_color_hex(0xFBE8C9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayBtnBack1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomRelayBtnBack1, lv_color_hex(0xE3B171), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomRelayBtnBack1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayLabelBack = lv_label_create(ui_RoomRelayBtnBack1);
lv_obj_set_width( ui_RoomRelayLabelBack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomRelayLabelBack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RoomRelayLabelBack, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomRelayLabelBack,"返回");
lv_obj_set_style_text_color(ui_RoomRelayLabelBack, lv_color_hex(0x4C3911), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RoomRelayLabelBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RoomRelayLabelBack, &ui_font_CN32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayBtnOpen3 = lv_btn_create(ui_ScreenRoomRelay);
lv_obj_set_width( ui_RoomRelayBtnOpen3, 160);
lv_obj_set_height( ui_RoomRelayBtnOpen3, 150);
lv_obj_set_x( ui_RoomRelayBtnOpen3, 800 );
lv_obj_set_y( ui_RoomRelayBtnOpen3, 270 );
lv_obj_add_flag( ui_RoomRelayBtnOpen3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomRelayBtnOpen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomRelayBtnOpen3, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayBtnOpen3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomRelayBtnOpen3, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomRelayBtnOpen3, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomRelayBtnOpen3, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomRelayBtnOpen3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomRelayBtnOpen3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayLabelOpen2 = lv_label_create(ui_RoomRelayBtnOpen3);
lv_obj_set_width( ui_RoomRelayLabelOpen2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomRelayLabelOpen2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomRelayLabelOpen2, 0 );
lv_obj_set_y( ui_RoomRelayLabelOpen2, 45 );
lv_obj_set_align( ui_RoomRelayLabelOpen2, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomRelayLabelOpen2,"调色");
lv_obj_set_style_text_font(ui_RoomRelayLabelOpen2, &ui_font_CN24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayIconOpen2 = lv_btn_create(ui_RoomRelayBtnOpen3);
lv_obj_set_width( ui_RoomRelayIconOpen2, 80);
lv_obj_set_height( ui_RoomRelayIconOpen2, 80);
lv_obj_set_x( ui_RoomRelayIconOpen2, 0 );
lv_obj_set_y( ui_RoomRelayIconOpen2, -15 );
lv_obj_set_align( ui_RoomRelayIconOpen2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoomRelayIconOpen2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomRelayIconOpen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomRelayIconOpen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayIconOpen2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_RoomRelayIconOpen2, &ui_img_130793449, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RoomRelayBtnRelay9 = lv_btn_create(ui_ScreenRoomRelay);
lv_obj_set_width( ui_RoomRelayBtnRelay9, 160);
lv_obj_set_height( ui_RoomRelayBtnRelay9, 210);
lv_obj_set_x( ui_RoomRelayBtnRelay9, 40 );
lv_obj_set_y( ui_RoomRelayBtnRelay9, 100 );
lv_obj_add_flag( ui_RoomRelayBtnRelay9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomRelayBtnRelay9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomRelayBtnRelay9, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayBtnRelay9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomRelayBtnRelay9, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomRelayBtnRelay9, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomRelayBtnRelay9, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomRelayBtnRelay9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomRelayBtnRelay9, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayLabelRelay9 = lv_label_create(ui_RoomRelayBtnRelay9);
lv_obj_set_width( ui_RoomRelayLabelRelay9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomRelayLabelRelay9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomRelayLabelRelay9, 0 );
lv_obj_set_y( ui_RoomRelayLabelRelay9, -30 );
lv_obj_set_align( ui_RoomRelayLabelRelay9, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomRelayLabelRelay9,"吊灯");
lv_obj_set_style_text_font(ui_RoomRelayLabelRelay9, &ui_font_CN32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelaySwRelay9 = lv_switch_create(ui_RoomRelayBtnRelay9);
lv_obj_set_width( ui_RoomRelaySwRelay9, 100);
lv_obj_set_height( ui_RoomRelaySwRelay9, 40);
lv_obj_set_x( ui_RoomRelaySwRelay9, 0 );
lv_obj_set_y( ui_RoomRelaySwRelay9, 40 );
lv_obj_set_align( ui_RoomRelaySwRelay9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RoomRelaySwRelay9, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_bg_color(ui_RoomRelaySwRelay9, lv_color_hex(0x857D66), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay9, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomRelaySwRelay9, lv_color_hex(0xE0AE67), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay9, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_RoomRelayBtnRelay11 = lv_btn_create(ui_ScreenRoomRelay);
lv_obj_set_width( ui_RoomRelayBtnRelay11, 160);
lv_obj_set_height( ui_RoomRelayBtnRelay11, 210);
lv_obj_set_x( ui_RoomRelayBtnRelay11, 610 );
lv_obj_set_y( ui_RoomRelayBtnRelay11, 100 );
lv_obj_add_flag( ui_RoomRelayBtnRelay11, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomRelayBtnRelay11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomRelayBtnRelay11, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayBtnRelay11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomRelayBtnRelay11, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomRelayBtnRelay11, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomRelayBtnRelay11, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomRelayBtnRelay11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomRelayBtnRelay11, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayLabelRelay11 = lv_label_create(ui_RoomRelayBtnRelay11);
lv_obj_set_width( ui_RoomRelayLabelRelay11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomRelayLabelRelay11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomRelayLabelRelay11, 0 );
lv_obj_set_y( ui_RoomRelayLabelRelay11, -30 );
lv_obj_set_align( ui_RoomRelayLabelRelay11, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomRelayLabelRelay11,"台灯");
lv_obj_set_style_text_font(ui_RoomRelayLabelRelay11, &ui_font_CN32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelaySwRelay11 = lv_switch_create(ui_RoomRelayBtnRelay11);
lv_obj_set_width( ui_RoomRelaySwRelay11, 100);
lv_obj_set_height( ui_RoomRelaySwRelay11, 40);
lv_obj_set_x( ui_RoomRelaySwRelay11, 0 );
lv_obj_set_y( ui_RoomRelaySwRelay11, 40 );
lv_obj_set_align( ui_RoomRelaySwRelay11, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RoomRelaySwRelay11, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_bg_color(ui_RoomRelaySwRelay11, lv_color_hex(0x857D66), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay11, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomRelaySwRelay11, lv_color_hex(0xE0AE67), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay11, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_RoomRelayBtnRelay5 = lv_btn_create(ui_ScreenRoomRelay);
lv_obj_set_width( ui_RoomRelayBtnRelay5, 160);
lv_obj_set_height( ui_RoomRelayBtnRelay5, 210);
lv_obj_set_x( ui_RoomRelayBtnRelay5, 230 );
lv_obj_set_y( ui_RoomRelayBtnRelay5, 100 );
lv_obj_add_flag( ui_RoomRelayBtnRelay5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomRelayBtnRelay5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomRelayBtnRelay5, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayBtnRelay5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomRelayBtnRelay5, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomRelayBtnRelay5, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomRelayBtnRelay5, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomRelayBtnRelay5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomRelayBtnRelay5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayLabelRelay5 = lv_label_create(ui_RoomRelayBtnRelay5);
lv_obj_set_width( ui_RoomRelayLabelRelay5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomRelayLabelRelay5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomRelayLabelRelay5, 0 );
lv_obj_set_y( ui_RoomRelayLabelRelay5, -30 );
lv_obj_set_align( ui_RoomRelayLabelRelay5, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomRelayLabelRelay5,"LED灯带");
lv_obj_set_style_text_font(ui_RoomRelayLabelRelay5, &ui_font_CN32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelaySwRelay5 = lv_switch_create(ui_RoomRelayBtnRelay5);
lv_obj_set_width( ui_RoomRelaySwRelay5, 100);
lv_obj_set_height( ui_RoomRelaySwRelay5, 40);
lv_obj_set_x( ui_RoomRelaySwRelay5, 0 );
lv_obj_set_y( ui_RoomRelaySwRelay5, 40 );
lv_obj_set_align( ui_RoomRelaySwRelay5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RoomRelaySwRelay5, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_bg_color(ui_RoomRelaySwRelay5, lv_color_hex(0x857D66), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay5, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomRelaySwRelay5, lv_color_hex(0xE0AE67), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay5, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_RoomRelayBtnRelay10 = lv_btn_create(ui_ScreenRoomRelay);
lv_obj_set_width( ui_RoomRelayBtnRelay10, 160);
lv_obj_set_height( ui_RoomRelayBtnRelay10, 210);
lv_obj_set_x( ui_RoomRelayBtnRelay10, 420 );
lv_obj_set_y( ui_RoomRelayBtnRelay10, 100 );
lv_obj_add_flag( ui_RoomRelayBtnRelay10, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomRelayBtnRelay10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomRelayBtnRelay10, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayBtnRelay10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomRelayBtnRelay10, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomRelayBtnRelay10, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomRelayBtnRelay10, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomRelayBtnRelay10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomRelayBtnRelay10, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayLabelRelay10 = lv_label_create(ui_RoomRelayBtnRelay10);
lv_obj_set_width( ui_RoomRelayLabelRelay10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomRelayLabelRelay10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomRelayLabelRelay10, 0 );
lv_obj_set_y( ui_RoomRelayLabelRelay10, -30 );
lv_obj_set_align( ui_RoomRelayLabelRelay10, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomRelayLabelRelay10,"射灯");
lv_obj_set_style_text_font(ui_RoomRelayLabelRelay10, &ui_font_CN32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelaySwRelay10 = lv_switch_create(ui_RoomRelayBtnRelay10);
lv_obj_set_width( ui_RoomRelaySwRelay10, 100);
lv_obj_set_height( ui_RoomRelaySwRelay10, 40);
lv_obj_set_x( ui_RoomRelaySwRelay10, 0 );
lv_obj_set_y( ui_RoomRelaySwRelay10, 40 );
lv_obj_set_align( ui_RoomRelaySwRelay10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RoomRelaySwRelay10, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_bg_color(ui_RoomRelaySwRelay10, lv_color_hex(0x857D66), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay10, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomRelaySwRelay10, lv_color_hex(0xE0AE67), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay10, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_RoomRelayBtnRelay7 = lv_btn_create(ui_ScreenRoomRelay);
lv_obj_set_width( ui_RoomRelayBtnRelay7, 160);
lv_obj_set_height( ui_RoomRelayBtnRelay7, 210);
lv_obj_set_x( ui_RoomRelayBtnRelay7, 40 );
lv_obj_set_y( ui_RoomRelayBtnRelay7, 335 );
lv_obj_add_flag( ui_RoomRelayBtnRelay7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomRelayBtnRelay7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomRelayBtnRelay7, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayBtnRelay7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomRelayBtnRelay7, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomRelayBtnRelay7, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomRelayBtnRelay7, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomRelayBtnRelay7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomRelayBtnRelay7, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayLabelRelay7 = lv_label_create(ui_RoomRelayBtnRelay7);
lv_obj_set_width( ui_RoomRelayLabelRelay7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomRelayLabelRelay7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomRelayLabelRelay7, 0 );
lv_obj_set_y( ui_RoomRelayLabelRelay7, -30 );
lv_obj_set_align( ui_RoomRelayLabelRelay7, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomRelayLabelRelay7,"沙发");
lv_obj_set_style_text_font(ui_RoomRelayLabelRelay7, &ui_font_CN32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelaySwRelay7 = lv_switch_create(ui_RoomRelayBtnRelay7);
lv_obj_set_width( ui_RoomRelaySwRelay7, 100);
lv_obj_set_height( ui_RoomRelaySwRelay7, 40);
lv_obj_set_x( ui_RoomRelaySwRelay7, 0 );
lv_obj_set_y( ui_RoomRelaySwRelay7, 40 );
lv_obj_set_align( ui_RoomRelaySwRelay7, LV_ALIGN_CENTER );
lv_obj_add_state( ui_RoomRelaySwRelay7, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_RoomRelaySwRelay7, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_bg_color(ui_RoomRelaySwRelay7, lv_color_hex(0x857D66), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay7, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomRelaySwRelay7, lv_color_hex(0xE0AE67), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay7, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_RoomRelayBtnRelay8 = lv_btn_create(ui_ScreenRoomRelay);
lv_obj_set_width( ui_RoomRelayBtnRelay8, 160);
lv_obj_set_height( ui_RoomRelayBtnRelay8, 210);
lv_obj_set_x( ui_RoomRelayBtnRelay8, 230 );
lv_obj_set_y( ui_RoomRelayBtnRelay8, 335 );
lv_obj_add_flag( ui_RoomRelayBtnRelay8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomRelayBtnRelay8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomRelayBtnRelay8, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayBtnRelay8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomRelayBtnRelay8, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomRelayBtnRelay8, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomRelayBtnRelay8, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomRelayBtnRelay8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomRelayBtnRelay8, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayLabelRelay8 = lv_label_create(ui_RoomRelayBtnRelay8);
lv_obj_set_width( ui_RoomRelayLabelRelay8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomRelayLabelRelay8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomRelayLabelRelay8, 0 );
lv_obj_set_y( ui_RoomRelayLabelRelay8, -30 );
lv_obj_set_align( ui_RoomRelayLabelRelay8, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomRelayLabelRelay8,"电视");
lv_obj_set_style_text_font(ui_RoomRelayLabelRelay8, &ui_font_CN32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelaySwRelay8 = lv_switch_create(ui_RoomRelayBtnRelay8);
lv_obj_set_width( ui_RoomRelaySwRelay8, 100);
lv_obj_set_height( ui_RoomRelaySwRelay8, 40);
lv_obj_set_x( ui_RoomRelaySwRelay8, 0 );
lv_obj_set_y( ui_RoomRelaySwRelay8, 40 );
lv_obj_set_align( ui_RoomRelaySwRelay8, LV_ALIGN_CENTER );
lv_obj_add_state( ui_RoomRelaySwRelay8, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_RoomRelaySwRelay8, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_bg_color(ui_RoomRelaySwRelay8, lv_color_hex(0x857D66), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay8, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomRelaySwRelay8, lv_color_hex(0xE0AE67), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay8, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_RoomRelayBtnRelay12 = lv_btn_create(ui_ScreenRoomRelay);
lv_obj_set_width( ui_RoomRelayBtnRelay12, 160);
lv_obj_set_height( ui_RoomRelayBtnRelay12, 210);
lv_obj_set_x( ui_RoomRelayBtnRelay12, 420 );
lv_obj_set_y( ui_RoomRelayBtnRelay12, 335 );
lv_obj_add_flag( ui_RoomRelayBtnRelay12, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomRelayBtnRelay12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomRelayBtnRelay12, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayBtnRelay12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomRelayBtnRelay12, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomRelayBtnRelay12, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomRelayBtnRelay12, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomRelayBtnRelay12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomRelayBtnRelay12, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayLabelRelay12 = lv_label_create(ui_RoomRelayBtnRelay12);
lv_obj_set_width( ui_RoomRelayLabelRelay12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomRelayLabelRelay12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomRelayLabelRelay12, 0 );
lv_obj_set_y( ui_RoomRelayLabelRelay12, -30 );
lv_obj_set_align( ui_RoomRelayLabelRelay12, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomRelayLabelRelay12,"卫生间");
lv_obj_set_style_text_font(ui_RoomRelayLabelRelay12, &ui_font_CN32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelaySwRelay12 = lv_switch_create(ui_RoomRelayBtnRelay12);
lv_obj_set_width( ui_RoomRelaySwRelay12, 100);
lv_obj_set_height( ui_RoomRelaySwRelay12, 40);
lv_obj_set_x( ui_RoomRelaySwRelay12, 0 );
lv_obj_set_y( ui_RoomRelaySwRelay12, 40 );
lv_obj_set_align( ui_RoomRelaySwRelay12, LV_ALIGN_CENTER );
lv_obj_add_state( ui_RoomRelaySwRelay12, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_RoomRelaySwRelay12, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_bg_color(ui_RoomRelaySwRelay12, lv_color_hex(0x857D66), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay12, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomRelaySwRelay12, lv_color_hex(0xE0AE67), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay12, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_RoomRelayBtnRelay13 = lv_btn_create(ui_ScreenRoomRelay);
lv_obj_set_width( ui_RoomRelayBtnRelay13, 160);
lv_obj_set_height( ui_RoomRelayBtnRelay13, 210);
lv_obj_set_x( ui_RoomRelayBtnRelay13, 610 );
lv_obj_set_y( ui_RoomRelayBtnRelay13, 335 );
lv_obj_add_flag( ui_RoomRelayBtnRelay13, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RoomRelayBtnRelay13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RoomRelayBtnRelay13, lv_color_hex(0x22211D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelayBtnRelay13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RoomRelayBtnRelay13, lv_color_hex(0x726551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RoomRelayBtnRelay13, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomRelayBtnRelay13, lv_color_hex(0x725F5A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomRelayBtnRelay13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomRelayBtnRelay13, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelayLabelRelay13 = lv_label_create(ui_RoomRelayBtnRelay13);
lv_obj_set_width( ui_RoomRelayLabelRelay13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomRelayLabelRelay13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomRelayLabelRelay13, 0 );
lv_obj_set_y( ui_RoomRelayLabelRelay13, -30 );
lv_obj_set_align( ui_RoomRelayLabelRelay13, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoomRelayLabelRelay13,"排风扇");
lv_obj_set_style_text_font(ui_RoomRelayLabelRelay13, &ui_font_CN32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomRelaySwRelay13 = lv_switch_create(ui_RoomRelayBtnRelay13);
lv_obj_set_width( ui_RoomRelaySwRelay13, 100);
lv_obj_set_height( ui_RoomRelaySwRelay13, 40);
lv_obj_set_x( ui_RoomRelaySwRelay13, 0 );
lv_obj_set_y( ui_RoomRelaySwRelay13, 40 );
lv_obj_set_align( ui_RoomRelaySwRelay13, LV_ALIGN_CENTER );
lv_obj_add_state( ui_RoomRelaySwRelay13, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_RoomRelaySwRelay13, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_bg_color(ui_RoomRelaySwRelay13, lv_color_hex(0x857D66), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay13, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomRelaySwRelay13, lv_color_hex(0xE0AE67), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_RoomRelaySwRelay13, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);


}
